// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AttackHitEffectResult.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from AttackHitEffectResult.proto</summary>
  public static partial class AttackHitEffectResultReflection {

    #region Descriptor
    /// <summary>File descriptor for AttackHitEffectResult.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AttackHitEffectResultReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtBdHRhY2tIaXRFZmZlY3RSZXN1bHQucHJvdG8SH1dlZWR3YWNrZXIuU2hh",
            "cmVkLk5ldHdvcmsuUHJvdG8ixQEKFUF0dGFja0hpdEVmZmVjdFJlc3VsdBIb",
            "ChNVbmszMzAwX0RBQkdER0xBSUtMGA0gASgCEhsKE1VuazMzMDBfSkRFRkhN",
            "S0lDUEYYCiABKAISGwoTVW5rMzMwMF9FQ0hPRkJMR0lJTxgJIAEoAhIbChNV",
            "bmszMzAwX0xDS0VDSkNLS0pLGAggASgNEhsKE1VuazMzMDBfS0xOR0RBTU1G",
            "SUYYASABKA0SGwoTVW5rMzMwMF9NTkdDT0FJR0dBTBgDIAEoAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Shared.Network.Proto.AttackHitEffectResult), global::Weedwacker.Shared.Network.Proto.AttackHitEffectResult.Parser, new[]{ "Unk3300DABGDGLAIKL", "Unk3300JDEFHMKICPF", "Unk3300ECHOFBLGIIO", "Unk3300LCKECJCKKJK", "Unk3300KLNGDAMMFIF", "Unk3300MNGCOAIGGAL" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class AttackHitEffectResult : pb::IMessage<AttackHitEffectResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AttackHitEffectResult> _parser = new pb::MessageParser<AttackHitEffectResult>(() => new AttackHitEffectResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AttackHitEffectResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Shared.Network.Proto.AttackHitEffectResultReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AttackHitEffectResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AttackHitEffectResult(AttackHitEffectResult other) : this() {
      unk3300DABGDGLAIKL_ = other.unk3300DABGDGLAIKL_;
      unk3300JDEFHMKICPF_ = other.unk3300JDEFHMKICPF_;
      unk3300ECHOFBLGIIO_ = other.unk3300ECHOFBLGIIO_;
      unk3300LCKECJCKKJK_ = other.unk3300LCKECJCKKJK_;
      unk3300KLNGDAMMFIF_ = other.unk3300KLNGDAMMFIF_;
      unk3300MNGCOAIGGAL_ = other.unk3300MNGCOAIGGAL_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AttackHitEffectResult Clone() {
      return new AttackHitEffectResult(this);
    }

    /// <summary>Field number for the "Unk3300_DABGDGLAIKL" field.</summary>
    public const int Unk3300DABGDGLAIKLFieldNumber = 13;
    private float unk3300DABGDGLAIKL_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Unk3300DABGDGLAIKL {
      get { return unk3300DABGDGLAIKL_; }
      set {
        unk3300DABGDGLAIKL_ = value;
      }
    }

    /// <summary>Field number for the "Unk3300_JDEFHMKICPF" field.</summary>
    public const int Unk3300JDEFHMKICPFFieldNumber = 10;
    private float unk3300JDEFHMKICPF_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Unk3300JDEFHMKICPF {
      get { return unk3300JDEFHMKICPF_; }
      set {
        unk3300JDEFHMKICPF_ = value;
      }
    }

    /// <summary>Field number for the "Unk3300_ECHOFBLGIIO" field.</summary>
    public const int Unk3300ECHOFBLGIIOFieldNumber = 9;
    private float unk3300ECHOFBLGIIO_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Unk3300ECHOFBLGIIO {
      get { return unk3300ECHOFBLGIIO_; }
      set {
        unk3300ECHOFBLGIIO_ = value;
      }
    }

    /// <summary>Field number for the "Unk3300_LCKECJCKKJK" field.</summary>
    public const int Unk3300LCKECJCKKJKFieldNumber = 8;
    private uint unk3300LCKECJCKKJK_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Unk3300LCKECJCKKJK {
      get { return unk3300LCKECJCKKJK_; }
      set {
        unk3300LCKECJCKKJK_ = value;
      }
    }

    /// <summary>Field number for the "Unk3300_KLNGDAMMFIF" field.</summary>
    public const int Unk3300KLNGDAMMFIFFieldNumber = 1;
    private uint unk3300KLNGDAMMFIF_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Unk3300KLNGDAMMFIF {
      get { return unk3300KLNGDAMMFIF_; }
      set {
        unk3300KLNGDAMMFIF_ = value;
      }
    }

    /// <summary>Field number for the "Unk3300_MNGCOAIGGAL" field.</summary>
    public const int Unk3300MNGCOAIGGALFieldNumber = 3;
    private float unk3300MNGCOAIGGAL_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Unk3300MNGCOAIGGAL {
      get { return unk3300MNGCOAIGGAL_; }
      set {
        unk3300MNGCOAIGGAL_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AttackHitEffectResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AttackHitEffectResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Unk3300DABGDGLAIKL, other.Unk3300DABGDGLAIKL)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Unk3300JDEFHMKICPF, other.Unk3300JDEFHMKICPF)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Unk3300ECHOFBLGIIO, other.Unk3300ECHOFBLGIIO)) return false;
      if (Unk3300LCKECJCKKJK != other.Unk3300LCKECJCKKJK) return false;
      if (Unk3300KLNGDAMMFIF != other.Unk3300KLNGDAMMFIF) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Unk3300MNGCOAIGGAL, other.Unk3300MNGCOAIGGAL)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Unk3300DABGDGLAIKL != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Unk3300DABGDGLAIKL);
      if (Unk3300JDEFHMKICPF != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Unk3300JDEFHMKICPF);
      if (Unk3300ECHOFBLGIIO != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Unk3300ECHOFBLGIIO);
      if (Unk3300LCKECJCKKJK != 0) hash ^= Unk3300LCKECJCKKJK.GetHashCode();
      if (Unk3300KLNGDAMMFIF != 0) hash ^= Unk3300KLNGDAMMFIF.GetHashCode();
      if (Unk3300MNGCOAIGGAL != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Unk3300MNGCOAIGGAL);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Unk3300KLNGDAMMFIF != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Unk3300KLNGDAMMFIF);
      }
      if (Unk3300MNGCOAIGGAL != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Unk3300MNGCOAIGGAL);
      }
      if (Unk3300LCKECJCKKJK != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(Unk3300LCKECJCKKJK);
      }
      if (Unk3300ECHOFBLGIIO != 0F) {
        output.WriteRawTag(77);
        output.WriteFloat(Unk3300ECHOFBLGIIO);
      }
      if (Unk3300JDEFHMKICPF != 0F) {
        output.WriteRawTag(85);
        output.WriteFloat(Unk3300JDEFHMKICPF);
      }
      if (Unk3300DABGDGLAIKL != 0F) {
        output.WriteRawTag(109);
        output.WriteFloat(Unk3300DABGDGLAIKL);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Unk3300KLNGDAMMFIF != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Unk3300KLNGDAMMFIF);
      }
      if (Unk3300MNGCOAIGGAL != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Unk3300MNGCOAIGGAL);
      }
      if (Unk3300LCKECJCKKJK != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(Unk3300LCKECJCKKJK);
      }
      if (Unk3300ECHOFBLGIIO != 0F) {
        output.WriteRawTag(77);
        output.WriteFloat(Unk3300ECHOFBLGIIO);
      }
      if (Unk3300JDEFHMKICPF != 0F) {
        output.WriteRawTag(85);
        output.WriteFloat(Unk3300JDEFHMKICPF);
      }
      if (Unk3300DABGDGLAIKL != 0F) {
        output.WriteRawTag(109);
        output.WriteFloat(Unk3300DABGDGLAIKL);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Unk3300DABGDGLAIKL != 0F) {
        size += 1 + 4;
      }
      if (Unk3300JDEFHMKICPF != 0F) {
        size += 1 + 4;
      }
      if (Unk3300ECHOFBLGIIO != 0F) {
        size += 1 + 4;
      }
      if (Unk3300LCKECJCKKJK != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Unk3300LCKECJCKKJK);
      }
      if (Unk3300KLNGDAMMFIF != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Unk3300KLNGDAMMFIF);
      }
      if (Unk3300MNGCOAIGGAL != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AttackHitEffectResult other) {
      if (other == null) {
        return;
      }
      if (other.Unk3300DABGDGLAIKL != 0F) {
        Unk3300DABGDGLAIKL = other.Unk3300DABGDGLAIKL;
      }
      if (other.Unk3300JDEFHMKICPF != 0F) {
        Unk3300JDEFHMKICPF = other.Unk3300JDEFHMKICPF;
      }
      if (other.Unk3300ECHOFBLGIIO != 0F) {
        Unk3300ECHOFBLGIIO = other.Unk3300ECHOFBLGIIO;
      }
      if (other.Unk3300LCKECJCKKJK != 0) {
        Unk3300LCKECJCKKJK = other.Unk3300LCKECJCKKJK;
      }
      if (other.Unk3300KLNGDAMMFIF != 0) {
        Unk3300KLNGDAMMFIF = other.Unk3300KLNGDAMMFIF;
      }
      if (other.Unk3300MNGCOAIGGAL != 0F) {
        Unk3300MNGCOAIGGAL = other.Unk3300MNGCOAIGGAL;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Unk3300KLNGDAMMFIF = input.ReadUInt32();
            break;
          }
          case 29: {
            Unk3300MNGCOAIGGAL = input.ReadFloat();
            break;
          }
          case 64: {
            Unk3300LCKECJCKKJK = input.ReadUInt32();
            break;
          }
          case 77: {
            Unk3300ECHOFBLGIIO = input.ReadFloat();
            break;
          }
          case 85: {
            Unk3300JDEFHMKICPF = input.ReadFloat();
            break;
          }
          case 109: {
            Unk3300DABGDGLAIKL = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Unk3300KLNGDAMMFIF = input.ReadUInt32();
            break;
          }
          case 29: {
            Unk3300MNGCOAIGGAL = input.ReadFloat();
            break;
          }
          case 64: {
            Unk3300LCKECJCKKJK = input.ReadUInt32();
            break;
          }
          case 77: {
            Unk3300ECHOFBLGIIO = input.ReadFloat();
            break;
          }
          case 85: {
            Unk3300JDEFHMKICPF = input.ReadFloat();
            break;
          }
          case 109: {
            Unk3300DABGDGLAIKL = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
