// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CheckAddItemExceedLimitNotify.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from CheckAddItemExceedLimitNotify.proto</summary>
  public static partial class CheckAddItemExceedLimitNotifyReflection {

    #region Descriptor
    /// <summary>File descriptor for CheckAddItemExceedLimitNotify.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CheckAddItemExceedLimitNotifyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNDaGVja0FkZEl0ZW1FeGNlZWRMaW1pdE5vdGlmeS5wcm90bxIfV2VlZHdh",
            "Y2tlci5TaGFyZWQuTmV0d29yay5Qcm90byKiAwodQ2hlY2tBZGRJdGVtRXhj",
            "ZWVkTGltaXROb3RpZnkSGwoTVW5rMzMwMF9QS0pNRUpLQVBCSRgEIAMoDRIb",
            "ChNVbmszMzAwX0dQRFBDSkxIQkRFGAsgAygNEg4KBnJlYXNvbhgJIAEoDRIP",
            "Cgdpc19kcm9wGA4gASgIEmcKCG1zZ190eXBlGAYgASgOMlUuV2VlZHdhY2tl",
            "ci5TaGFyZWQuTmV0d29yay5Qcm90by5DaGVja0FkZEl0ZW1FeGNlZWRMaW1p",
            "dE5vdGlmeS5JdGVtRXhjZWVkTGltaXRNc2dUeXBlIrwBChZJdGVtRXhjZWVk",
            "TGltaXRNc2dUeXBlEiYKIklURU1fRVhDRUVEX0xJTUlUX01TR19UWVBFX0RF",
            "RkFVTFQQABIjCh9JVEVNX0VYQ0VFRF9MSU1JVF9NU0dfVFlQRV9URVhUEAES",
            "JQohSVRFTV9FWENFRURfTElNSVRfTVNHX1RZUEVfRElBTE9HEAISLgoqSVRF",
            "TV9FWENFRURfTElNSVRfTVNHX1RZUEVfRElBTE9HX05PTkJMT0NLEANiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Shared.Network.Proto.CheckAddItemExceedLimitNotify), global::Weedwacker.Shared.Network.Proto.CheckAddItemExceedLimitNotify.Parser, new[]{ "Unk3300PKJMEJKAPBI", "Unk3300GPDPCJLHBDE", "Reason", "IsDrop", "MsgType" }, null, new[]{ typeof(global::Weedwacker.Shared.Network.Proto.CheckAddItemExceedLimitNotify.Types.ItemExceedLimitMsgType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// enum CmdId {
  ///   option allow_alias = true;
  ///   NONE = 0;
  ///   CMD_ID = 697;
  ///   ENET_CHANNEL_ID = 0;
  ///   ENET_IS_RELIABLE = 1;
  /// }
  /// </summary>
  public sealed partial class CheckAddItemExceedLimitNotify : pb::IMessage<CheckAddItemExceedLimitNotify>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CheckAddItemExceedLimitNotify> _parser = new pb::MessageParser<CheckAddItemExceedLimitNotify>(() => new CheckAddItemExceedLimitNotify());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CheckAddItemExceedLimitNotify> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Shared.Network.Proto.CheckAddItemExceedLimitNotifyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CheckAddItemExceedLimitNotify() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CheckAddItemExceedLimitNotify(CheckAddItemExceedLimitNotify other) : this() {
      unk3300PKJMEJKAPBI_ = other.unk3300PKJMEJKAPBI_.Clone();
      unk3300GPDPCJLHBDE_ = other.unk3300GPDPCJLHBDE_.Clone();
      reason_ = other.reason_;
      isDrop_ = other.isDrop_;
      msgType_ = other.msgType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CheckAddItemExceedLimitNotify Clone() {
      return new CheckAddItemExceedLimitNotify(this);
    }

    /// <summary>Field number for the "Unk3300_PKJMEJKAPBI" field.</summary>
    public const int Unk3300PKJMEJKAPBIFieldNumber = 4;
    private static readonly pb::FieldCodec<uint> _repeated_unk3300PKJMEJKAPBI_codec
        = pb::FieldCodec.ForUInt32(34);
    private readonly pbc::RepeatedField<uint> unk3300PKJMEJKAPBI_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> Unk3300PKJMEJKAPBI {
      get { return unk3300PKJMEJKAPBI_; }
    }

    /// <summary>Field number for the "Unk3300_GPDPCJLHBDE" field.</summary>
    public const int Unk3300GPDPCJLHBDEFieldNumber = 11;
    private static readonly pb::FieldCodec<uint> _repeated_unk3300GPDPCJLHBDE_codec
        = pb::FieldCodec.ForUInt32(90);
    private readonly pbc::RepeatedField<uint> unk3300GPDPCJLHBDE_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> Unk3300GPDPCJLHBDE {
      get { return unk3300GPDPCJLHBDE_; }
    }

    /// <summary>Field number for the "reason" field.</summary>
    public const int ReasonFieldNumber = 9;
    private uint reason_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Reason {
      get { return reason_; }
      set {
        reason_ = value;
      }
    }

    /// <summary>Field number for the "is_drop" field.</summary>
    public const int IsDropFieldNumber = 14;
    private bool isDrop_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsDrop {
      get { return isDrop_; }
      set {
        isDrop_ = value;
      }
    }

    /// <summary>Field number for the "msg_type" field.</summary>
    public const int MsgTypeFieldNumber = 6;
    private global::Weedwacker.Shared.Network.Proto.CheckAddItemExceedLimitNotify.Types.ItemExceedLimitMsgType msgType_ = global::Weedwacker.Shared.Network.Proto.CheckAddItemExceedLimitNotify.Types.ItemExceedLimitMsgType.Default;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Shared.Network.Proto.CheckAddItemExceedLimitNotify.Types.ItemExceedLimitMsgType MsgType {
      get { return msgType_; }
      set {
        msgType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CheckAddItemExceedLimitNotify);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CheckAddItemExceedLimitNotify other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!unk3300PKJMEJKAPBI_.Equals(other.unk3300PKJMEJKAPBI_)) return false;
      if(!unk3300GPDPCJLHBDE_.Equals(other.unk3300GPDPCJLHBDE_)) return false;
      if (Reason != other.Reason) return false;
      if (IsDrop != other.IsDrop) return false;
      if (MsgType != other.MsgType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= unk3300PKJMEJKAPBI_.GetHashCode();
      hash ^= unk3300GPDPCJLHBDE_.GetHashCode();
      if (Reason != 0) hash ^= Reason.GetHashCode();
      if (IsDrop != false) hash ^= IsDrop.GetHashCode();
      if (MsgType != global::Weedwacker.Shared.Network.Proto.CheckAddItemExceedLimitNotify.Types.ItemExceedLimitMsgType.Default) hash ^= MsgType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      unk3300PKJMEJKAPBI_.WriteTo(output, _repeated_unk3300PKJMEJKAPBI_codec);
      if (MsgType != global::Weedwacker.Shared.Network.Proto.CheckAddItemExceedLimitNotify.Types.ItemExceedLimitMsgType.Default) {
        output.WriteRawTag(48);
        output.WriteEnum((int) MsgType);
      }
      if (Reason != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(Reason);
      }
      unk3300GPDPCJLHBDE_.WriteTo(output, _repeated_unk3300GPDPCJLHBDE_codec);
      if (IsDrop != false) {
        output.WriteRawTag(112);
        output.WriteBool(IsDrop);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      unk3300PKJMEJKAPBI_.WriteTo(ref output, _repeated_unk3300PKJMEJKAPBI_codec);
      if (MsgType != global::Weedwacker.Shared.Network.Proto.CheckAddItemExceedLimitNotify.Types.ItemExceedLimitMsgType.Default) {
        output.WriteRawTag(48);
        output.WriteEnum((int) MsgType);
      }
      if (Reason != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(Reason);
      }
      unk3300GPDPCJLHBDE_.WriteTo(ref output, _repeated_unk3300GPDPCJLHBDE_codec);
      if (IsDrop != false) {
        output.WriteRawTag(112);
        output.WriteBool(IsDrop);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += unk3300PKJMEJKAPBI_.CalculateSize(_repeated_unk3300PKJMEJKAPBI_codec);
      size += unk3300GPDPCJLHBDE_.CalculateSize(_repeated_unk3300GPDPCJLHBDE_codec);
      if (Reason != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Reason);
      }
      if (IsDrop != false) {
        size += 1 + 1;
      }
      if (MsgType != global::Weedwacker.Shared.Network.Proto.CheckAddItemExceedLimitNotify.Types.ItemExceedLimitMsgType.Default) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MsgType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CheckAddItemExceedLimitNotify other) {
      if (other == null) {
        return;
      }
      unk3300PKJMEJKAPBI_.Add(other.unk3300PKJMEJKAPBI_);
      unk3300GPDPCJLHBDE_.Add(other.unk3300GPDPCJLHBDE_);
      if (other.Reason != 0) {
        Reason = other.Reason;
      }
      if (other.IsDrop != false) {
        IsDrop = other.IsDrop;
      }
      if (other.MsgType != global::Weedwacker.Shared.Network.Proto.CheckAddItemExceedLimitNotify.Types.ItemExceedLimitMsgType.Default) {
        MsgType = other.MsgType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 34:
          case 32: {
            unk3300PKJMEJKAPBI_.AddEntriesFrom(input, _repeated_unk3300PKJMEJKAPBI_codec);
            break;
          }
          case 48: {
            MsgType = (global::Weedwacker.Shared.Network.Proto.CheckAddItemExceedLimitNotify.Types.ItemExceedLimitMsgType) input.ReadEnum();
            break;
          }
          case 72: {
            Reason = input.ReadUInt32();
            break;
          }
          case 90:
          case 88: {
            unk3300GPDPCJLHBDE_.AddEntriesFrom(input, _repeated_unk3300GPDPCJLHBDE_codec);
            break;
          }
          case 112: {
            IsDrop = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 34:
          case 32: {
            unk3300PKJMEJKAPBI_.AddEntriesFrom(ref input, _repeated_unk3300PKJMEJKAPBI_codec);
            break;
          }
          case 48: {
            MsgType = (global::Weedwacker.Shared.Network.Proto.CheckAddItemExceedLimitNotify.Types.ItemExceedLimitMsgType) input.ReadEnum();
            break;
          }
          case 72: {
            Reason = input.ReadUInt32();
            break;
          }
          case 90:
          case 88: {
            unk3300GPDPCJLHBDE_.AddEntriesFrom(ref input, _repeated_unk3300GPDPCJLHBDE_codec);
            break;
          }
          case 112: {
            IsDrop = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the CheckAddItemExceedLimitNotify message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum ItemExceedLimitMsgType {
        [pbr::OriginalName("ITEM_EXCEED_LIMIT_MSG_TYPE_DEFAULT")] Default = 0,
        [pbr::OriginalName("ITEM_EXCEED_LIMIT_MSG_TYPE_TEXT")] Text = 1,
        [pbr::OriginalName("ITEM_EXCEED_LIMIT_MSG_TYPE_DIALOG")] Dialog = 2,
        [pbr::OriginalName("ITEM_EXCEED_LIMIT_MSG_TYPE_DIALOG_NONBLOCK")] DialogNonblock = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
