// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CombatTypeArgument.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from CombatTypeArgument.proto</summary>
  public static partial class CombatTypeArgumentReflection {

    #region Descriptor
    /// <summary>File descriptor for CombatTypeArgument.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CombatTypeArgumentReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhDb21iYXRUeXBlQXJndW1lbnQucHJvdG8SH1dlZWR3YWNrZXIuU2hhcmVk",
            "Lk5ldHdvcmsuUHJvdG8qyAYKEkNvbWJhdFR5cGVBcmd1bWVudBIdChlDT01C",
            "QVRfVFlQRV9BUkdVTUVOVF9OT05FEAASJgoiQ09NQkFUX1RZUEVfQVJHVU1F",
            "TlRfRVZUX0JFSU5HX0hJVBABEi8KK0NPTUJBVF9UWVBFX0FSR1VNRU5UX0FO",
            "SU1BVE9SX1NUQVRFX0NIQU5HRUQQAhIkCiBDT01CQVRfVFlQRV9BUkdVTUVO",
            "VF9GQUNFX1RPX0RJUhADEioKJkNPTUJBVF9UWVBFX0FSR1VNRU5UX1NFVF9B",
            "VFRBQ0tfVEFSR0VUEAQSIgoeQ09NQkFUX1RZUEVfQVJHVU1FTlRfUlVTSF9N",
            "T1ZFEAUSMwovQ09NQkFUX1RZUEVfQVJHVU1FTlRfQU5JTUFUT1JfUEFSQU1F",
            "VEVSX0NIQU5HRUQQBhIkCiBDT01CQVRfVFlQRV9BUkdVTUVOVF9FTlRJVFlf",
            "TU9WRRAHEi0KKUNPTUJBVF9UWVBFX0FSR1VNRU5UX1NZTkNfRU5USVRZX1BP",
            "U0lUSU9OEAgSKgomQ09NQkFUX1RZUEVfQVJHVU1FTlRfU1RFRVJfTU9USU9O",
            "X0lORk8QCRIrCidDT01CQVRfVFlQRV9BUkdVTUVOVF9GT1JDRV9TRVRfUE9T",
            "X0lORk8QChIsCihDT01CQVRfVFlQRV9BUkdVTUVOVF9DT01QRU5TQVRFX1BP",
            "U19ESUZGEAsSKQolQ09NQkFUX1RZUEVfQVJHVU1FTlRfTU9OU1RFUl9ET19C",
            "TElOSxAMEigKJENPTUJBVF9UWVBFX0FSR1VNRU5UX0ZJWEVEX1JVU0hfTU9W",
            "RRANEicKI0NPTUJBVF9UWVBFX0FSR1VNRU5UX1NZTkNfVFJBTlNGT1JNEA4S",
            "KAokQ09NQkFUX1RZUEVfQVJHVU1FTlRfTElHSFRfQ09SRV9NT1ZFEA8SKQol",
            "Q09NQkFUX1RZUEVfQVJHVU1FTlRfQkVJTkdfSEVBTEVEX05URhAQEjIKLkNP",
            "TUJBVF9UWVBFX0FSR1VNRU5UX1NLSUxMX0FOQ0hPUl9QT1NJVElPTl9OVEYQ",
            "ERIsCihDT01CQVRfVFlQRV9BUkdVTUVOVF9HUkFQUExJTkdfSE9PS19NT1ZF",
            "EBJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Weedwacker.Shared.Network.Proto.CombatTypeArgument), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum CombatTypeArgument {
    [pbr::OriginalName("COMBAT_TYPE_ARGUMENT_NONE")] None = 0,
    [pbr::OriginalName("COMBAT_TYPE_ARGUMENT_EVT_BEING_HIT")] EvtBeingHit = 1,
    [pbr::OriginalName("COMBAT_TYPE_ARGUMENT_ANIMATOR_STATE_CHANGED")] AnimatorStateChanged = 2,
    [pbr::OriginalName("COMBAT_TYPE_ARGUMENT_FACE_TO_DIR")] FaceToDir = 3,
    [pbr::OriginalName("COMBAT_TYPE_ARGUMENT_SET_ATTACK_TARGET")] SetAttackTarget = 4,
    [pbr::OriginalName("COMBAT_TYPE_ARGUMENT_RUSH_MOVE")] RushMove = 5,
    [pbr::OriginalName("COMBAT_TYPE_ARGUMENT_ANIMATOR_PARAMETER_CHANGED")] AnimatorParameterChanged = 6,
    [pbr::OriginalName("COMBAT_TYPE_ARGUMENT_ENTITY_MOVE")] EntityMove = 7,
    [pbr::OriginalName("COMBAT_TYPE_ARGUMENT_SYNC_ENTITY_POSITION")] SyncEntityPosition = 8,
    [pbr::OriginalName("COMBAT_TYPE_ARGUMENT_STEER_MOTION_INFO")] SteerMotionInfo = 9,
    [pbr::OriginalName("COMBAT_TYPE_ARGUMENT_FORCE_SET_POS_INFO")] ForceSetPosInfo = 10,
    [pbr::OriginalName("COMBAT_TYPE_ARGUMENT_COMPENSATE_POS_DIFF")] CompensatePosDiff = 11,
    [pbr::OriginalName("COMBAT_TYPE_ARGUMENT_MONSTER_DO_BLINK")] MonsterDoBlink = 12,
    [pbr::OriginalName("COMBAT_TYPE_ARGUMENT_FIXED_RUSH_MOVE")] FixedRushMove = 13,
    [pbr::OriginalName("COMBAT_TYPE_ARGUMENT_SYNC_TRANSFORM")] SyncTransform = 14,
    [pbr::OriginalName("COMBAT_TYPE_ARGUMENT_LIGHT_CORE_MOVE")] LightCoreMove = 15,
    [pbr::OriginalName("COMBAT_TYPE_ARGUMENT_BEING_HEALED_NTF")] BeingHealedNtf = 16,
    [pbr::OriginalName("COMBAT_TYPE_ARGUMENT_SKILL_ANCHOR_POSITION_NTF")] SkillAnchorPositionNtf = 17,
    [pbr::OriginalName("COMBAT_TYPE_ARGUMENT_GRAPPLING_HOOK_MOVE")] GrapplingHookMove = 18,
  }

  #endregion

}

#endregion Designer generated code
