// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: EntityFightPropChangeReasonNotify.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from EntityFightPropChangeReasonNotify.proto</summary>
  public static partial class EntityFightPropChangeReasonNotifyReflection {

    #region Descriptor
    /// <summary>File descriptor for EntityFightPropChangeReasonNotify.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EntityFightPropChangeReasonNotifyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CidFbnRpdHlGaWdodFByb3BDaGFuZ2VSZWFzb25Ob3RpZnkucHJvdG8SH1dl",
            "ZWR3YWNrZXIuU2hhcmVkLk5ldHdvcmsuUHJvdG8aGENoYW5nZUVuZXJneVJl",
            "YXNvbi5wcm90bxoUQ2hhbmdlSHBSZWFzb24ucHJvdG8aFlByb3BDaGFuZ2VS",
            "ZWFzb24ucHJvdG8i0gIKIUVudGl0eUZpZ2h0UHJvcENoYW5nZVJlYXNvbk5v",
            "dGlmeRIRCglwcm9wX3R5cGUYBSABKA0SEgoKcGFyYW1fbGlzdBgHIAMoDRIR",
            "CgllbnRpdHlfaWQYCCABKA0SQQoGcmVhc29uGAIgASgOMjEuV2VlZHdhY2tl",
            "ci5TaGFyZWQuTmV0d29yay5Qcm90by5Qcm9wQ2hhbmdlUmVhc29uEkkKEGNo",
            "YW5nZV9ocF9yZWFzb24YCSABKA4yLy5XZWVkd2Fja2VyLlNoYXJlZC5OZXR3",
            "b3JrLlByb3RvLkNoYW5nZUhwUmVhc29uElEKFGNoYW5nZV9lbmVyZ3lfcmVh",
            "c29uGAwgASgOMjMuV2VlZHdhY2tlci5TaGFyZWQuTmV0d29yay5Qcm90by5D",
            "aGFuZ2VFbmVyZ3lSZWFzb24SEgoKcHJvcF9kZWx0YRgKIAEoAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Weedwacker.Shared.Network.Proto.ChangeEnergyReasonReflection.Descriptor, global::Weedwacker.Shared.Network.Proto.ChangeHpReasonReflection.Descriptor, global::Weedwacker.Shared.Network.Proto.PropChangeReasonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Shared.Network.Proto.EntityFightPropChangeReasonNotify), global::Weedwacker.Shared.Network.Proto.EntityFightPropChangeReasonNotify.Parser, new[]{ "PropType", "ParamList", "EntityId", "Reason", "ChangeHpReason", "ChangeEnergyReason", "PropDelta" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// enum CmdId {
  ///   option allow_alias = true;
  ///   NONE = 0;
  ///   CMD_ID = 1261;
  ///   ENET_CHANNEL_ID = 0;
  ///   ENET_IS_RELIABLE = 1;
  /// }
  /// </summary>
  public sealed partial class EntityFightPropChangeReasonNotify : pb::IMessage<EntityFightPropChangeReasonNotify>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntityFightPropChangeReasonNotify> _parser = new pb::MessageParser<EntityFightPropChangeReasonNotify>(() => new EntityFightPropChangeReasonNotify());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EntityFightPropChangeReasonNotify> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Shared.Network.Proto.EntityFightPropChangeReasonNotifyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityFightPropChangeReasonNotify() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityFightPropChangeReasonNotify(EntityFightPropChangeReasonNotify other) : this() {
      propType_ = other.propType_;
      paramList_ = other.paramList_.Clone();
      entityId_ = other.entityId_;
      reason_ = other.reason_;
      changeHpReason_ = other.changeHpReason_;
      changeEnergyReason_ = other.changeEnergyReason_;
      propDelta_ = other.propDelta_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityFightPropChangeReasonNotify Clone() {
      return new EntityFightPropChangeReasonNotify(this);
    }

    /// <summary>Field number for the "prop_type" field.</summary>
    public const int PropTypeFieldNumber = 5;
    private uint propType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PropType {
      get { return propType_; }
      set {
        propType_ = value;
      }
    }

    /// <summary>Field number for the "param_list" field.</summary>
    public const int ParamListFieldNumber = 7;
    private static readonly pb::FieldCodec<uint> _repeated_paramList_codec
        = pb::FieldCodec.ForUInt32(58);
    private readonly pbc::RepeatedField<uint> paramList_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> ParamList {
      get { return paramList_; }
    }

    /// <summary>Field number for the "entity_id" field.</summary>
    public const int EntityIdFieldNumber = 8;
    private uint entityId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EntityId {
      get { return entityId_; }
      set {
        entityId_ = value;
      }
    }

    /// <summary>Field number for the "reason" field.</summary>
    public const int ReasonFieldNumber = 2;
    private global::Weedwacker.Shared.Network.Proto.PropChangeReason reason_ = global::Weedwacker.Shared.Network.Proto.PropChangeReason.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Shared.Network.Proto.PropChangeReason Reason {
      get { return reason_; }
      set {
        reason_ = value;
      }
    }

    /// <summary>Field number for the "change_hp_reason" field.</summary>
    public const int ChangeHpReasonFieldNumber = 9;
    private global::Weedwacker.Shared.Network.Proto.ChangeHpReason changeHpReason_ = global::Weedwacker.Shared.Network.Proto.ChangeHpReason.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Shared.Network.Proto.ChangeHpReason ChangeHpReason {
      get { return changeHpReason_; }
      set {
        changeHpReason_ = value;
      }
    }

    /// <summary>Field number for the "change_energy_reason" field.</summary>
    public const int ChangeEnergyReasonFieldNumber = 12;
    private global::Weedwacker.Shared.Network.Proto.ChangeEnergyReason changeEnergyReason_ = global::Weedwacker.Shared.Network.Proto.ChangeEnergyReason.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Shared.Network.Proto.ChangeEnergyReason ChangeEnergyReason {
      get { return changeEnergyReason_; }
      set {
        changeEnergyReason_ = value;
      }
    }

    /// <summary>Field number for the "prop_delta" field.</summary>
    public const int PropDeltaFieldNumber = 10;
    private float propDelta_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float PropDelta {
      get { return propDelta_; }
      set {
        propDelta_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EntityFightPropChangeReasonNotify);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EntityFightPropChangeReasonNotify other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PropType != other.PropType) return false;
      if(!paramList_.Equals(other.paramList_)) return false;
      if (EntityId != other.EntityId) return false;
      if (Reason != other.Reason) return false;
      if (ChangeHpReason != other.ChangeHpReason) return false;
      if (ChangeEnergyReason != other.ChangeEnergyReason) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PropDelta, other.PropDelta)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PropType != 0) hash ^= PropType.GetHashCode();
      hash ^= paramList_.GetHashCode();
      if (EntityId != 0) hash ^= EntityId.GetHashCode();
      if (Reason != global::Weedwacker.Shared.Network.Proto.PropChangeReason.None) hash ^= Reason.GetHashCode();
      if (ChangeHpReason != global::Weedwacker.Shared.Network.Proto.ChangeHpReason.None) hash ^= ChangeHpReason.GetHashCode();
      if (ChangeEnergyReason != global::Weedwacker.Shared.Network.Proto.ChangeEnergyReason.None) hash ^= ChangeEnergyReason.GetHashCode();
      if (PropDelta != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PropDelta);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Reason != global::Weedwacker.Shared.Network.Proto.PropChangeReason.None) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Reason);
      }
      if (PropType != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(PropType);
      }
      paramList_.WriteTo(output, _repeated_paramList_codec);
      if (EntityId != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(EntityId);
      }
      if (ChangeHpReason != global::Weedwacker.Shared.Network.Proto.ChangeHpReason.None) {
        output.WriteRawTag(72);
        output.WriteEnum((int) ChangeHpReason);
      }
      if (PropDelta != 0F) {
        output.WriteRawTag(85);
        output.WriteFloat(PropDelta);
      }
      if (ChangeEnergyReason != global::Weedwacker.Shared.Network.Proto.ChangeEnergyReason.None) {
        output.WriteRawTag(96);
        output.WriteEnum((int) ChangeEnergyReason);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Reason != global::Weedwacker.Shared.Network.Proto.PropChangeReason.None) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Reason);
      }
      if (PropType != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(PropType);
      }
      paramList_.WriteTo(ref output, _repeated_paramList_codec);
      if (EntityId != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(EntityId);
      }
      if (ChangeHpReason != global::Weedwacker.Shared.Network.Proto.ChangeHpReason.None) {
        output.WriteRawTag(72);
        output.WriteEnum((int) ChangeHpReason);
      }
      if (PropDelta != 0F) {
        output.WriteRawTag(85);
        output.WriteFloat(PropDelta);
      }
      if (ChangeEnergyReason != global::Weedwacker.Shared.Network.Proto.ChangeEnergyReason.None) {
        output.WriteRawTag(96);
        output.WriteEnum((int) ChangeEnergyReason);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PropType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PropType);
      }
      size += paramList_.CalculateSize(_repeated_paramList_codec);
      if (EntityId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EntityId);
      }
      if (Reason != global::Weedwacker.Shared.Network.Proto.PropChangeReason.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Reason);
      }
      if (ChangeHpReason != global::Weedwacker.Shared.Network.Proto.ChangeHpReason.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ChangeHpReason);
      }
      if (ChangeEnergyReason != global::Weedwacker.Shared.Network.Proto.ChangeEnergyReason.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ChangeEnergyReason);
      }
      if (PropDelta != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EntityFightPropChangeReasonNotify other) {
      if (other == null) {
        return;
      }
      if (other.PropType != 0) {
        PropType = other.PropType;
      }
      paramList_.Add(other.paramList_);
      if (other.EntityId != 0) {
        EntityId = other.EntityId;
      }
      if (other.Reason != global::Weedwacker.Shared.Network.Proto.PropChangeReason.None) {
        Reason = other.Reason;
      }
      if (other.ChangeHpReason != global::Weedwacker.Shared.Network.Proto.ChangeHpReason.None) {
        ChangeHpReason = other.ChangeHpReason;
      }
      if (other.ChangeEnergyReason != global::Weedwacker.Shared.Network.Proto.ChangeEnergyReason.None) {
        ChangeEnergyReason = other.ChangeEnergyReason;
      }
      if (other.PropDelta != 0F) {
        PropDelta = other.PropDelta;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            Reason = (global::Weedwacker.Shared.Network.Proto.PropChangeReason) input.ReadEnum();
            break;
          }
          case 40: {
            PropType = input.ReadUInt32();
            break;
          }
          case 58:
          case 56: {
            paramList_.AddEntriesFrom(input, _repeated_paramList_codec);
            break;
          }
          case 64: {
            EntityId = input.ReadUInt32();
            break;
          }
          case 72: {
            ChangeHpReason = (global::Weedwacker.Shared.Network.Proto.ChangeHpReason) input.ReadEnum();
            break;
          }
          case 85: {
            PropDelta = input.ReadFloat();
            break;
          }
          case 96: {
            ChangeEnergyReason = (global::Weedwacker.Shared.Network.Proto.ChangeEnergyReason) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 16: {
            Reason = (global::Weedwacker.Shared.Network.Proto.PropChangeReason) input.ReadEnum();
            break;
          }
          case 40: {
            PropType = input.ReadUInt32();
            break;
          }
          case 58:
          case 56: {
            paramList_.AddEntriesFrom(ref input, _repeated_paramList_codec);
            break;
          }
          case 64: {
            EntityId = input.ReadUInt32();
            break;
          }
          case 72: {
            ChangeHpReason = (global::Weedwacker.Shared.Network.Proto.ChangeHpReason) input.ReadEnum();
            break;
          }
          case 85: {
            PropDelta = input.ReadFloat();
            break;
          }
          case 96: {
            ChangeEnergyReason = (global::Weedwacker.Shared.Network.Proto.ChangeEnergyReason) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
