// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GCGDSDataNotify.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from GCGDSDataNotify.proto</summary>
  public static partial class GCGDSDataNotifyReflection {

    #region Descriptor
    /// <summary>File descriptor for GCGDSDataNotify.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GCGDSDataNotifyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVHQ0dEU0RhdGFOb3RpZnkucHJvdG8SH1dlZWR3YWNrZXIuU2hhcmVkLk5l",
            "dHdvcmsuUHJvdG8aE0dDR0RTQ2FyZERhdGEucHJvdG8aE0dDR0RTRGVja0Rh",
            "dGEucHJvdG8igwIKD0dDR0RTRGF0YU5vdGlmeRITCgtjdXJfZGVja19pZBgI",
            "IAEoDRJBCglkZWNrX2xpc3QYAyADKAsyLi5XZWVkd2Fja2VyLlNoYXJlZC5O",
            "ZXR3b3JrLlByb3RvLkdDR0RTRGVja0RhdGESGwoTVW5rMzMwMF9HRUJISkFH",
            "S0VJRBgKIAMoDRJBCgljYXJkX2xpc3QYCSADKAsyLi5XZWVkd2Fja2VyLlNo",
            "YXJlZC5OZXR3b3JrLlByb3RvLkdDR0RTQ2FyZERhdGESGwoTVW5rMzMwMF9B",
            "QUVBRUNHUEhCSBgFIAMoDRIbChNVbmszMzAwX0pKQ0VJTkZIS09HGAYgAygN",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Weedwacker.Shared.Network.Proto.GCGDSCardDataReflection.Descriptor, global::Weedwacker.Shared.Network.Proto.GCGDSDeckDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Shared.Network.Proto.GCGDSDataNotify), global::Weedwacker.Shared.Network.Proto.GCGDSDataNotify.Parser, new[]{ "CurDeckId", "DeckList", "Unk3300GEBHJAGKEID", "CardList", "Unk3300AAEAECGPHBH", "Unk3300JJCEINFHKOG" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// enum CmdId {
  ///   option allow_alias = true;
  ///   NONE = 0;
  ///   CMD_ID = 7850;
  ///   ENET_CHANNEL_ID = 0;
  ///   ENET_IS_RELIABLE = 1;
  /// }
  /// </summary>
  public sealed partial class GCGDSDataNotify : pb::IMessage<GCGDSDataNotify>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GCGDSDataNotify> _parser = new pb::MessageParser<GCGDSDataNotify>(() => new GCGDSDataNotify());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GCGDSDataNotify> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Shared.Network.Proto.GCGDSDataNotifyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GCGDSDataNotify() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GCGDSDataNotify(GCGDSDataNotify other) : this() {
      curDeckId_ = other.curDeckId_;
      deckList_ = other.deckList_.Clone();
      unk3300GEBHJAGKEID_ = other.unk3300GEBHJAGKEID_.Clone();
      cardList_ = other.cardList_.Clone();
      unk3300AAEAECGPHBH_ = other.unk3300AAEAECGPHBH_.Clone();
      unk3300JJCEINFHKOG_ = other.unk3300JJCEINFHKOG_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GCGDSDataNotify Clone() {
      return new GCGDSDataNotify(this);
    }

    /// <summary>Field number for the "cur_deck_id" field.</summary>
    public const int CurDeckIdFieldNumber = 8;
    private uint curDeckId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CurDeckId {
      get { return curDeckId_; }
      set {
        curDeckId_ = value;
      }
    }

    /// <summary>Field number for the "deck_list" field.</summary>
    public const int DeckListFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Weedwacker.Shared.Network.Proto.GCGDSDeckData> _repeated_deckList_codec
        = pb::FieldCodec.ForMessage(26, global::Weedwacker.Shared.Network.Proto.GCGDSDeckData.Parser);
    private readonly pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.GCGDSDeckData> deckList_ = new pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.GCGDSDeckData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.GCGDSDeckData> DeckList {
      get { return deckList_; }
    }

    /// <summary>Field number for the "Unk3300_GEBHJAGKEID" field.</summary>
    public const int Unk3300GEBHJAGKEIDFieldNumber = 10;
    private static readonly pb::FieldCodec<uint> _repeated_unk3300GEBHJAGKEID_codec
        = pb::FieldCodec.ForUInt32(82);
    private readonly pbc::RepeatedField<uint> unk3300GEBHJAGKEID_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> Unk3300GEBHJAGKEID {
      get { return unk3300GEBHJAGKEID_; }
    }

    /// <summary>Field number for the "card_list" field.</summary>
    public const int CardListFieldNumber = 9;
    private static readonly pb::FieldCodec<global::Weedwacker.Shared.Network.Proto.GCGDSCardData> _repeated_cardList_codec
        = pb::FieldCodec.ForMessage(74, global::Weedwacker.Shared.Network.Proto.GCGDSCardData.Parser);
    private readonly pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.GCGDSCardData> cardList_ = new pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.GCGDSCardData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.GCGDSCardData> CardList {
      get { return cardList_; }
    }

    /// <summary>Field number for the "Unk3300_AAEAECGPHBH" field.</summary>
    public const int Unk3300AAEAECGPHBHFieldNumber = 5;
    private static readonly pb::FieldCodec<uint> _repeated_unk3300AAEAECGPHBH_codec
        = pb::FieldCodec.ForUInt32(42);
    private readonly pbc::RepeatedField<uint> unk3300AAEAECGPHBH_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> Unk3300AAEAECGPHBH {
      get { return unk3300AAEAECGPHBH_; }
    }

    /// <summary>Field number for the "Unk3300_JJCEINFHKOG" field.</summary>
    public const int Unk3300JJCEINFHKOGFieldNumber = 6;
    private static readonly pb::FieldCodec<uint> _repeated_unk3300JJCEINFHKOG_codec
        = pb::FieldCodec.ForUInt32(50);
    private readonly pbc::RepeatedField<uint> unk3300JJCEINFHKOG_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> Unk3300JJCEINFHKOG {
      get { return unk3300JJCEINFHKOG_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GCGDSDataNotify);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GCGDSDataNotify other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CurDeckId != other.CurDeckId) return false;
      if(!deckList_.Equals(other.deckList_)) return false;
      if(!unk3300GEBHJAGKEID_.Equals(other.unk3300GEBHJAGKEID_)) return false;
      if(!cardList_.Equals(other.cardList_)) return false;
      if(!unk3300AAEAECGPHBH_.Equals(other.unk3300AAEAECGPHBH_)) return false;
      if(!unk3300JJCEINFHKOG_.Equals(other.unk3300JJCEINFHKOG_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CurDeckId != 0) hash ^= CurDeckId.GetHashCode();
      hash ^= deckList_.GetHashCode();
      hash ^= unk3300GEBHJAGKEID_.GetHashCode();
      hash ^= cardList_.GetHashCode();
      hash ^= unk3300AAEAECGPHBH_.GetHashCode();
      hash ^= unk3300JJCEINFHKOG_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      deckList_.WriteTo(output, _repeated_deckList_codec);
      unk3300AAEAECGPHBH_.WriteTo(output, _repeated_unk3300AAEAECGPHBH_codec);
      unk3300JJCEINFHKOG_.WriteTo(output, _repeated_unk3300JJCEINFHKOG_codec);
      if (CurDeckId != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(CurDeckId);
      }
      cardList_.WriteTo(output, _repeated_cardList_codec);
      unk3300GEBHJAGKEID_.WriteTo(output, _repeated_unk3300GEBHJAGKEID_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      deckList_.WriteTo(ref output, _repeated_deckList_codec);
      unk3300AAEAECGPHBH_.WriteTo(ref output, _repeated_unk3300AAEAECGPHBH_codec);
      unk3300JJCEINFHKOG_.WriteTo(ref output, _repeated_unk3300JJCEINFHKOG_codec);
      if (CurDeckId != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(CurDeckId);
      }
      cardList_.WriteTo(ref output, _repeated_cardList_codec);
      unk3300GEBHJAGKEID_.WriteTo(ref output, _repeated_unk3300GEBHJAGKEID_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CurDeckId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CurDeckId);
      }
      size += deckList_.CalculateSize(_repeated_deckList_codec);
      size += unk3300GEBHJAGKEID_.CalculateSize(_repeated_unk3300GEBHJAGKEID_codec);
      size += cardList_.CalculateSize(_repeated_cardList_codec);
      size += unk3300AAEAECGPHBH_.CalculateSize(_repeated_unk3300AAEAECGPHBH_codec);
      size += unk3300JJCEINFHKOG_.CalculateSize(_repeated_unk3300JJCEINFHKOG_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GCGDSDataNotify other) {
      if (other == null) {
        return;
      }
      if (other.CurDeckId != 0) {
        CurDeckId = other.CurDeckId;
      }
      deckList_.Add(other.deckList_);
      unk3300GEBHJAGKEID_.Add(other.unk3300GEBHJAGKEID_);
      cardList_.Add(other.cardList_);
      unk3300AAEAECGPHBH_.Add(other.unk3300AAEAECGPHBH_);
      unk3300JJCEINFHKOG_.Add(other.unk3300JJCEINFHKOG_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 26: {
            deckList_.AddEntriesFrom(input, _repeated_deckList_codec);
            break;
          }
          case 42:
          case 40: {
            unk3300AAEAECGPHBH_.AddEntriesFrom(input, _repeated_unk3300AAEAECGPHBH_codec);
            break;
          }
          case 50:
          case 48: {
            unk3300JJCEINFHKOG_.AddEntriesFrom(input, _repeated_unk3300JJCEINFHKOG_codec);
            break;
          }
          case 64: {
            CurDeckId = input.ReadUInt32();
            break;
          }
          case 74: {
            cardList_.AddEntriesFrom(input, _repeated_cardList_codec);
            break;
          }
          case 82:
          case 80: {
            unk3300GEBHJAGKEID_.AddEntriesFrom(input, _repeated_unk3300GEBHJAGKEID_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 26: {
            deckList_.AddEntriesFrom(ref input, _repeated_deckList_codec);
            break;
          }
          case 42:
          case 40: {
            unk3300AAEAECGPHBH_.AddEntriesFrom(ref input, _repeated_unk3300AAEAECGPHBH_codec);
            break;
          }
          case 50:
          case 48: {
            unk3300JJCEINFHKOG_.AddEntriesFrom(ref input, _repeated_unk3300JJCEINFHKOG_codec);
            break;
          }
          case 64: {
            CurDeckId = input.ReadUInt32();
            break;
          }
          case 74: {
            cardList_.AddEntriesFrom(ref input, _repeated_cardList_codec);
            break;
          }
          case 82:
          case 80: {
            unk3300GEBHJAGKEID_.AddEntriesFrom(ref input, _repeated_unk3300GEBHJAGKEID_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
