// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GCGTavernNpcInfoNotify.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from GCGTavernNpcInfoNotify.proto</summary>
  public static partial class GCGTavernNpcInfoNotifyReflection {

    #region Descriptor
    /// <summary>File descriptor for GCGTavernNpcInfoNotify.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GCGTavernNpcInfoNotifyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxHQ0dUYXZlcm5OcGNJbmZvTm90aWZ5LnByb3RvEh9XZWVkd2Fja2VyLlNo",
            "YXJlZC5OZXR3b3JrLlByb3RvGhZHQ0dUYXZlcm5OcGNJbmZvLnByb3RvIoIC",
            "ChZHQ0dUYXZlcm5OcGNJbmZvTm90aWZ5Ek4KE1VuazMzMDBfRktBS0hNTUlF",
            "QkMYDCADKAsyMS5XZWVkd2Fja2VyLlNoYXJlZC5OZXR3b3JrLlByb3RvLkdD",
            "R1RhdmVybk5wY0luZm8STgoTVW5rMzMwMF9CQU1MTkVORExDTRgCIAMoCzIx",
            "LldlZWR3YWNrZXIuU2hhcmVkLk5ldHdvcmsuUHJvdG8uR0NHVGF2ZXJuTnBj",
            "SW5mbxJICg1jaGFyYWN0ZXJfbnBjGAsgASgLMjEuV2VlZHdhY2tlci5TaGFy",
            "ZWQuTmV0d29yay5Qcm90by5HQ0dUYXZlcm5OcGNJbmZvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Weedwacker.Shared.Network.Proto.GCGTavernNpcInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Shared.Network.Proto.GCGTavernNpcInfoNotify), global::Weedwacker.Shared.Network.Proto.GCGTavernNpcInfoNotify.Parser, new[]{ "Unk3300FKAKHMMIEBC", "Unk3300BAMLNENDLCM", "CharacterNpc" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// enum CmdId {
  ///   option allow_alias = true;
  ///   NONE = 0;
  ///   CMD_ID = 7267;
  ///   ENET_CHANNEL_ID = 0;
  ///   ENET_IS_RELIABLE = 1;
  /// }
  /// </summary>
  public sealed partial class GCGTavernNpcInfoNotify : pb::IMessage<GCGTavernNpcInfoNotify>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GCGTavernNpcInfoNotify> _parser = new pb::MessageParser<GCGTavernNpcInfoNotify>(() => new GCGTavernNpcInfoNotify());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GCGTavernNpcInfoNotify> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Shared.Network.Proto.GCGTavernNpcInfoNotifyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GCGTavernNpcInfoNotify() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GCGTavernNpcInfoNotify(GCGTavernNpcInfoNotify other) : this() {
      unk3300FKAKHMMIEBC_ = other.unk3300FKAKHMMIEBC_.Clone();
      unk3300BAMLNENDLCM_ = other.unk3300BAMLNENDLCM_.Clone();
      characterNpc_ = other.characterNpc_ != null ? other.characterNpc_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GCGTavernNpcInfoNotify Clone() {
      return new GCGTavernNpcInfoNotify(this);
    }

    /// <summary>Field number for the "Unk3300_FKAKHMMIEBC" field.</summary>
    public const int Unk3300FKAKHMMIEBCFieldNumber = 12;
    private static readonly pb::FieldCodec<global::Weedwacker.Shared.Network.Proto.GCGTavernNpcInfo> _repeated_unk3300FKAKHMMIEBC_codec
        = pb::FieldCodec.ForMessage(98, global::Weedwacker.Shared.Network.Proto.GCGTavernNpcInfo.Parser);
    private readonly pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.GCGTavernNpcInfo> unk3300FKAKHMMIEBC_ = new pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.GCGTavernNpcInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.GCGTavernNpcInfo> Unk3300FKAKHMMIEBC {
      get { return unk3300FKAKHMMIEBC_; }
    }

    /// <summary>Field number for the "Unk3300_BAMLNENDLCM" field.</summary>
    public const int Unk3300BAMLNENDLCMFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Weedwacker.Shared.Network.Proto.GCGTavernNpcInfo> _repeated_unk3300BAMLNENDLCM_codec
        = pb::FieldCodec.ForMessage(18, global::Weedwacker.Shared.Network.Proto.GCGTavernNpcInfo.Parser);
    private readonly pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.GCGTavernNpcInfo> unk3300BAMLNENDLCM_ = new pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.GCGTavernNpcInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.GCGTavernNpcInfo> Unk3300BAMLNENDLCM {
      get { return unk3300BAMLNENDLCM_; }
    }

    /// <summary>Field number for the "character_npc" field.</summary>
    public const int CharacterNpcFieldNumber = 11;
    private global::Weedwacker.Shared.Network.Proto.GCGTavernNpcInfo characterNpc_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Shared.Network.Proto.GCGTavernNpcInfo CharacterNpc {
      get { return characterNpc_; }
      set {
        characterNpc_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GCGTavernNpcInfoNotify);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GCGTavernNpcInfoNotify other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!unk3300FKAKHMMIEBC_.Equals(other.unk3300FKAKHMMIEBC_)) return false;
      if(!unk3300BAMLNENDLCM_.Equals(other.unk3300BAMLNENDLCM_)) return false;
      if (!object.Equals(CharacterNpc, other.CharacterNpc)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= unk3300FKAKHMMIEBC_.GetHashCode();
      hash ^= unk3300BAMLNENDLCM_.GetHashCode();
      if (characterNpc_ != null) hash ^= CharacterNpc.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      unk3300BAMLNENDLCM_.WriteTo(output, _repeated_unk3300BAMLNENDLCM_codec);
      if (characterNpc_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(CharacterNpc);
      }
      unk3300FKAKHMMIEBC_.WriteTo(output, _repeated_unk3300FKAKHMMIEBC_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      unk3300BAMLNENDLCM_.WriteTo(ref output, _repeated_unk3300BAMLNENDLCM_codec);
      if (characterNpc_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(CharacterNpc);
      }
      unk3300FKAKHMMIEBC_.WriteTo(ref output, _repeated_unk3300FKAKHMMIEBC_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += unk3300FKAKHMMIEBC_.CalculateSize(_repeated_unk3300FKAKHMMIEBC_codec);
      size += unk3300BAMLNENDLCM_.CalculateSize(_repeated_unk3300BAMLNENDLCM_codec);
      if (characterNpc_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CharacterNpc);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GCGTavernNpcInfoNotify other) {
      if (other == null) {
        return;
      }
      unk3300FKAKHMMIEBC_.Add(other.unk3300FKAKHMMIEBC_);
      unk3300BAMLNENDLCM_.Add(other.unk3300BAMLNENDLCM_);
      if (other.characterNpc_ != null) {
        if (characterNpc_ == null) {
          CharacterNpc = new global::Weedwacker.Shared.Network.Proto.GCGTavernNpcInfo();
        }
        CharacterNpc.MergeFrom(other.CharacterNpc);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            unk3300BAMLNENDLCM_.AddEntriesFrom(input, _repeated_unk3300BAMLNENDLCM_codec);
            break;
          }
          case 90: {
            if (characterNpc_ == null) {
              CharacterNpc = new global::Weedwacker.Shared.Network.Proto.GCGTavernNpcInfo();
            }
            input.ReadMessage(CharacterNpc);
            break;
          }
          case 98: {
            unk3300FKAKHMMIEBC_.AddEntriesFrom(input, _repeated_unk3300FKAKHMMIEBC_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            unk3300BAMLNENDLCM_.AddEntriesFrom(ref input, _repeated_unk3300BAMLNENDLCM_codec);
            break;
          }
          case 90: {
            if (characterNpc_ == null) {
              CharacterNpc = new global::Weedwacker.Shared.Network.Proto.GCGTavernNpcInfo();
            }
            input.ReadMessage(CharacterNpc);
            break;
          }
          case 98: {
            unk3300FKAKHMMIEBC_.AddEntriesFrom(ref input, _repeated_unk3300FKAKHMMIEBC_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
