// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GetCityReputationMapInfoRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from GetCityReputationMapInfoRsp.proto</summary>
  public static partial class GetCityReputationMapInfoRspReflection {

    #region Descriptor
    /// <summary>File descriptor for GetCityReputationMapInfoRsp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GetCityReputationMapInfoRspReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFHZXRDaXR5UmVwdXRhdGlvbk1hcEluZm9Sc3AucHJvdG8SH1dlZWR3YWNr",
            "ZXIuU2hhcmVkLk5ldHdvcmsuUHJvdG8iogEKG0dldENpdHlSZXB1dGF0aW9u",
            "TWFwSW5mb1JzcBIPCgdyZXRjb2RlGA0gASgFEhsKE1VuazMzMDBfREFJR0hI",
            "UEpIT08YBCADKA0SGwoTVW5rMzMwMF9HSkZOT1BOTUZORxgMIAEoCBIbChNV",
            "bmszMzAwX05DTUhNT0RJSUtNGAUgASgIEhsKE1VuazMzMDBfUEFQQk9IS09N",
            "RksYDyADKA1iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Shared.Network.Proto.GetCityReputationMapInfoRsp), global::Weedwacker.Shared.Network.Proto.GetCityReputationMapInfoRsp.Parser, new[]{ "Retcode", "Unk3300DAIGHHPJHOO", "Unk3300GJFNOPNMFNG", "Unk3300NCMHMODIIKM", "Unk3300PAPBOHKOMFK" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// enum CmdId {
  ///   option allow_alias = true;
  ///   NONE = 0;
  ///   CMD_ID = 2848;
  ///   ENET_CHANNEL_ID = 0;
  ///   ENET_IS_RELIABLE = 1;
  /// }
  /// </summary>
  public sealed partial class GetCityReputationMapInfoRsp : pb::IMessage<GetCityReputationMapInfoRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetCityReputationMapInfoRsp> _parser = new pb::MessageParser<GetCityReputationMapInfoRsp>(() => new GetCityReputationMapInfoRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetCityReputationMapInfoRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Shared.Network.Proto.GetCityReputationMapInfoRspReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetCityReputationMapInfoRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetCityReputationMapInfoRsp(GetCityReputationMapInfoRsp other) : this() {
      retcode_ = other.retcode_;
      unk3300DAIGHHPJHOO_ = other.unk3300DAIGHHPJHOO_.Clone();
      unk3300GJFNOPNMFNG_ = other.unk3300GJFNOPNMFNG_;
      unk3300NCMHMODIIKM_ = other.unk3300NCMHMODIIKM_;
      unk3300PAPBOHKOMFK_ = other.unk3300PAPBOHKOMFK_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetCityReputationMapInfoRsp Clone() {
      return new GetCityReputationMapInfoRsp(this);
    }

    /// <summary>Field number for the "retcode" field.</summary>
    public const int RetcodeFieldNumber = 13;
    private int retcode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Retcode {
      get { return retcode_; }
      set {
        retcode_ = value;
      }
    }

    /// <summary>Field number for the "Unk3300_DAIGHHPJHOO" field.</summary>
    public const int Unk3300DAIGHHPJHOOFieldNumber = 4;
    private static readonly pb::FieldCodec<uint> _repeated_unk3300DAIGHHPJHOO_codec
        = pb::FieldCodec.ForUInt32(34);
    private readonly pbc::RepeatedField<uint> unk3300DAIGHHPJHOO_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> Unk3300DAIGHHPJHOO {
      get { return unk3300DAIGHHPJHOO_; }
    }

    /// <summary>Field number for the "Unk3300_GJFNOPNMFNG" field.</summary>
    public const int Unk3300GJFNOPNMFNGFieldNumber = 12;
    private bool unk3300GJFNOPNMFNG_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Unk3300GJFNOPNMFNG {
      get { return unk3300GJFNOPNMFNG_; }
      set {
        unk3300GJFNOPNMFNG_ = value;
      }
    }

    /// <summary>Field number for the "Unk3300_NCMHMODIIKM" field.</summary>
    public const int Unk3300NCMHMODIIKMFieldNumber = 5;
    private bool unk3300NCMHMODIIKM_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Unk3300NCMHMODIIKM {
      get { return unk3300NCMHMODIIKM_; }
      set {
        unk3300NCMHMODIIKM_ = value;
      }
    }

    /// <summary>Field number for the "Unk3300_PAPBOHKOMFK" field.</summary>
    public const int Unk3300PAPBOHKOMFKFieldNumber = 15;
    private static readonly pb::FieldCodec<uint> _repeated_unk3300PAPBOHKOMFK_codec
        = pb::FieldCodec.ForUInt32(122);
    private readonly pbc::RepeatedField<uint> unk3300PAPBOHKOMFK_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> Unk3300PAPBOHKOMFK {
      get { return unk3300PAPBOHKOMFK_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetCityReputationMapInfoRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetCityReputationMapInfoRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Retcode != other.Retcode) return false;
      if(!unk3300DAIGHHPJHOO_.Equals(other.unk3300DAIGHHPJHOO_)) return false;
      if (Unk3300GJFNOPNMFNG != other.Unk3300GJFNOPNMFNG) return false;
      if (Unk3300NCMHMODIIKM != other.Unk3300NCMHMODIIKM) return false;
      if(!unk3300PAPBOHKOMFK_.Equals(other.unk3300PAPBOHKOMFK_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Retcode != 0) hash ^= Retcode.GetHashCode();
      hash ^= unk3300DAIGHHPJHOO_.GetHashCode();
      if (Unk3300GJFNOPNMFNG != false) hash ^= Unk3300GJFNOPNMFNG.GetHashCode();
      if (Unk3300NCMHMODIIKM != false) hash ^= Unk3300NCMHMODIIKM.GetHashCode();
      hash ^= unk3300PAPBOHKOMFK_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      unk3300DAIGHHPJHOO_.WriteTo(output, _repeated_unk3300DAIGHHPJHOO_codec);
      if (Unk3300NCMHMODIIKM != false) {
        output.WriteRawTag(40);
        output.WriteBool(Unk3300NCMHMODIIKM);
      }
      if (Unk3300GJFNOPNMFNG != false) {
        output.WriteRawTag(96);
        output.WriteBool(Unk3300GJFNOPNMFNG);
      }
      if (Retcode != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(Retcode);
      }
      unk3300PAPBOHKOMFK_.WriteTo(output, _repeated_unk3300PAPBOHKOMFK_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      unk3300DAIGHHPJHOO_.WriteTo(ref output, _repeated_unk3300DAIGHHPJHOO_codec);
      if (Unk3300NCMHMODIIKM != false) {
        output.WriteRawTag(40);
        output.WriteBool(Unk3300NCMHMODIIKM);
      }
      if (Unk3300GJFNOPNMFNG != false) {
        output.WriteRawTag(96);
        output.WriteBool(Unk3300GJFNOPNMFNG);
      }
      if (Retcode != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(Retcode);
      }
      unk3300PAPBOHKOMFK_.WriteTo(ref output, _repeated_unk3300PAPBOHKOMFK_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Retcode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Retcode);
      }
      size += unk3300DAIGHHPJHOO_.CalculateSize(_repeated_unk3300DAIGHHPJHOO_codec);
      if (Unk3300GJFNOPNMFNG != false) {
        size += 1 + 1;
      }
      if (Unk3300NCMHMODIIKM != false) {
        size += 1 + 1;
      }
      size += unk3300PAPBOHKOMFK_.CalculateSize(_repeated_unk3300PAPBOHKOMFK_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetCityReputationMapInfoRsp other) {
      if (other == null) {
        return;
      }
      if (other.Retcode != 0) {
        Retcode = other.Retcode;
      }
      unk3300DAIGHHPJHOO_.Add(other.unk3300DAIGHHPJHOO_);
      if (other.Unk3300GJFNOPNMFNG != false) {
        Unk3300GJFNOPNMFNG = other.Unk3300GJFNOPNMFNG;
      }
      if (other.Unk3300NCMHMODIIKM != false) {
        Unk3300NCMHMODIIKM = other.Unk3300NCMHMODIIKM;
      }
      unk3300PAPBOHKOMFK_.Add(other.unk3300PAPBOHKOMFK_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 34:
          case 32: {
            unk3300DAIGHHPJHOO_.AddEntriesFrom(input, _repeated_unk3300DAIGHHPJHOO_codec);
            break;
          }
          case 40: {
            Unk3300NCMHMODIIKM = input.ReadBool();
            break;
          }
          case 96: {
            Unk3300GJFNOPNMFNG = input.ReadBool();
            break;
          }
          case 104: {
            Retcode = input.ReadInt32();
            break;
          }
          case 122:
          case 120: {
            unk3300PAPBOHKOMFK_.AddEntriesFrom(input, _repeated_unk3300PAPBOHKOMFK_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 34:
          case 32: {
            unk3300DAIGHHPJHOO_.AddEntriesFrom(ref input, _repeated_unk3300DAIGHHPJHOO_codec);
            break;
          }
          case 40: {
            Unk3300NCMHMODIIKM = input.ReadBool();
            break;
          }
          case 96: {
            Unk3300GJFNOPNMFNG = input.ReadBool();
            break;
          }
          case 104: {
            Retcode = input.ReadInt32();
            break;
          }
          case 122:
          case 120: {
            unk3300PAPBOHKOMFK_.AddEntriesFrom(ref input, _repeated_unk3300PAPBOHKOMFK_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
