// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: HitCollision.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from HitCollision.proto</summary>
  public static partial class HitCollisionReflection {

    #region Descriptor
    /// <summary>File descriptor for HitCollision.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HitCollisionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJIaXRDb2xsaXNpb24ucHJvdG8SH1dlZWR3YWNrZXIuU2hhcmVkLk5ldHdv",
            "cmsuUHJvdG8aFUhpdENvbGxpZGVyVHlwZS5wcm90bxoMVmVjdG9yLnByb3Rv",
            "IqICCgxIaXRDb2xsaXNpb24SFQoNaGl0X2JveF9pbmRleBgIIAEoBRJLChFo",
            "aXRfY29sbGlkZXJfdHlwZRgFIAEoDjIwLldlZWR3YWNrZXIuU2hhcmVkLk5l",
            "dHdvcmsuUHJvdG8uSGl0Q29sbGlkZXJUeXBlEhsKE1VuazMzMDBfTE5ISU9M",
            "Rk1HQ04YByABKAISOAoHaGl0X2RpchgDIAEoCzInLldlZWR3YWNrZXIuU2hh",
            "cmVkLk5ldHdvcmsuUHJvdG8uVmVjdG9yEjoKCWhpdF9wb2ludBgOIAEoCzIn",
            "LldlZWR3YWNrZXIuU2hhcmVkLk5ldHdvcmsuUHJvdG8uVmVjdG9yEhsKE1Vu",
            "azMzMDBfT0pIQk1MSUFQSk4YCiABKAJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Weedwacker.Shared.Network.Proto.HitColliderTypeReflection.Descriptor, global::Weedwacker.Shared.Network.Proto.VectorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Shared.Network.Proto.HitCollision), global::Weedwacker.Shared.Network.Proto.HitCollision.Parser, new[]{ "HitBoxIndex", "HitColliderType", "Unk3300LNHIOLFMGCN", "HitDir", "HitPoint", "Unk3300OJHBMLIAPJN" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class HitCollision : pb::IMessage<HitCollision>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HitCollision> _parser = new pb::MessageParser<HitCollision>(() => new HitCollision());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HitCollision> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Shared.Network.Proto.HitCollisionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HitCollision() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HitCollision(HitCollision other) : this() {
      hitBoxIndex_ = other.hitBoxIndex_;
      hitColliderType_ = other.hitColliderType_;
      unk3300LNHIOLFMGCN_ = other.unk3300LNHIOLFMGCN_;
      hitDir_ = other.hitDir_ != null ? other.hitDir_.Clone() : null;
      hitPoint_ = other.hitPoint_ != null ? other.hitPoint_.Clone() : null;
      unk3300OJHBMLIAPJN_ = other.unk3300OJHBMLIAPJN_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HitCollision Clone() {
      return new HitCollision(this);
    }

    /// <summary>Field number for the "hit_box_index" field.</summary>
    public const int HitBoxIndexFieldNumber = 8;
    private int hitBoxIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int HitBoxIndex {
      get { return hitBoxIndex_; }
      set {
        hitBoxIndex_ = value;
      }
    }

    /// <summary>Field number for the "hit_collider_type" field.</summary>
    public const int HitColliderTypeFieldNumber = 5;
    private global::Weedwacker.Shared.Network.Proto.HitColliderType hitColliderType_ = global::Weedwacker.Shared.Network.Proto.HitColliderType.Invalid;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Shared.Network.Proto.HitColliderType HitColliderType {
      get { return hitColliderType_; }
      set {
        hitColliderType_ = value;
      }
    }

    /// <summary>Field number for the "Unk3300_LNHIOLFMGCN" field.</summary>
    public const int Unk3300LNHIOLFMGCNFieldNumber = 7;
    private float unk3300LNHIOLFMGCN_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Unk3300LNHIOLFMGCN {
      get { return unk3300LNHIOLFMGCN_; }
      set {
        unk3300LNHIOLFMGCN_ = value;
      }
    }

    /// <summary>Field number for the "hit_dir" field.</summary>
    public const int HitDirFieldNumber = 3;
    private global::Weedwacker.Shared.Network.Proto.Vector hitDir_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Shared.Network.Proto.Vector HitDir {
      get { return hitDir_; }
      set {
        hitDir_ = value;
      }
    }

    /// <summary>Field number for the "hit_point" field.</summary>
    public const int HitPointFieldNumber = 14;
    private global::Weedwacker.Shared.Network.Proto.Vector hitPoint_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Shared.Network.Proto.Vector HitPoint {
      get { return hitPoint_; }
      set {
        hitPoint_ = value;
      }
    }

    /// <summary>Field number for the "Unk3300_OJHBMLIAPJN" field.</summary>
    public const int Unk3300OJHBMLIAPJNFieldNumber = 10;
    private float unk3300OJHBMLIAPJN_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Unk3300OJHBMLIAPJN {
      get { return unk3300OJHBMLIAPJN_; }
      set {
        unk3300OJHBMLIAPJN_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HitCollision);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HitCollision other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (HitBoxIndex != other.HitBoxIndex) return false;
      if (HitColliderType != other.HitColliderType) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Unk3300LNHIOLFMGCN, other.Unk3300LNHIOLFMGCN)) return false;
      if (!object.Equals(HitDir, other.HitDir)) return false;
      if (!object.Equals(HitPoint, other.HitPoint)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Unk3300OJHBMLIAPJN, other.Unk3300OJHBMLIAPJN)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HitBoxIndex != 0) hash ^= HitBoxIndex.GetHashCode();
      if (HitColliderType != global::Weedwacker.Shared.Network.Proto.HitColliderType.Invalid) hash ^= HitColliderType.GetHashCode();
      if (Unk3300LNHIOLFMGCN != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Unk3300LNHIOLFMGCN);
      if (hitDir_ != null) hash ^= HitDir.GetHashCode();
      if (hitPoint_ != null) hash ^= HitPoint.GetHashCode();
      if (Unk3300OJHBMLIAPJN != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Unk3300OJHBMLIAPJN);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (hitDir_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(HitDir);
      }
      if (HitColliderType != global::Weedwacker.Shared.Network.Proto.HitColliderType.Invalid) {
        output.WriteRawTag(40);
        output.WriteEnum((int) HitColliderType);
      }
      if (Unk3300LNHIOLFMGCN != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(Unk3300LNHIOLFMGCN);
      }
      if (HitBoxIndex != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(HitBoxIndex);
      }
      if (Unk3300OJHBMLIAPJN != 0F) {
        output.WriteRawTag(85);
        output.WriteFloat(Unk3300OJHBMLIAPJN);
      }
      if (hitPoint_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(HitPoint);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (hitDir_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(HitDir);
      }
      if (HitColliderType != global::Weedwacker.Shared.Network.Proto.HitColliderType.Invalid) {
        output.WriteRawTag(40);
        output.WriteEnum((int) HitColliderType);
      }
      if (Unk3300LNHIOLFMGCN != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(Unk3300LNHIOLFMGCN);
      }
      if (HitBoxIndex != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(HitBoxIndex);
      }
      if (Unk3300OJHBMLIAPJN != 0F) {
        output.WriteRawTag(85);
        output.WriteFloat(Unk3300OJHBMLIAPJN);
      }
      if (hitPoint_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(HitPoint);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HitBoxIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(HitBoxIndex);
      }
      if (HitColliderType != global::Weedwacker.Shared.Network.Proto.HitColliderType.Invalid) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) HitColliderType);
      }
      if (Unk3300LNHIOLFMGCN != 0F) {
        size += 1 + 4;
      }
      if (hitDir_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HitDir);
      }
      if (hitPoint_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HitPoint);
      }
      if (Unk3300OJHBMLIAPJN != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HitCollision other) {
      if (other == null) {
        return;
      }
      if (other.HitBoxIndex != 0) {
        HitBoxIndex = other.HitBoxIndex;
      }
      if (other.HitColliderType != global::Weedwacker.Shared.Network.Proto.HitColliderType.Invalid) {
        HitColliderType = other.HitColliderType;
      }
      if (other.Unk3300LNHIOLFMGCN != 0F) {
        Unk3300LNHIOLFMGCN = other.Unk3300LNHIOLFMGCN;
      }
      if (other.hitDir_ != null) {
        if (hitDir_ == null) {
          HitDir = new global::Weedwacker.Shared.Network.Proto.Vector();
        }
        HitDir.MergeFrom(other.HitDir);
      }
      if (other.hitPoint_ != null) {
        if (hitPoint_ == null) {
          HitPoint = new global::Weedwacker.Shared.Network.Proto.Vector();
        }
        HitPoint.MergeFrom(other.HitPoint);
      }
      if (other.Unk3300OJHBMLIAPJN != 0F) {
        Unk3300OJHBMLIAPJN = other.Unk3300OJHBMLIAPJN;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 26: {
            if (hitDir_ == null) {
              HitDir = new global::Weedwacker.Shared.Network.Proto.Vector();
            }
            input.ReadMessage(HitDir);
            break;
          }
          case 40: {
            HitColliderType = (global::Weedwacker.Shared.Network.Proto.HitColliderType) input.ReadEnum();
            break;
          }
          case 61: {
            Unk3300LNHIOLFMGCN = input.ReadFloat();
            break;
          }
          case 64: {
            HitBoxIndex = input.ReadInt32();
            break;
          }
          case 85: {
            Unk3300OJHBMLIAPJN = input.ReadFloat();
            break;
          }
          case 114: {
            if (hitPoint_ == null) {
              HitPoint = new global::Weedwacker.Shared.Network.Proto.Vector();
            }
            input.ReadMessage(HitPoint);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 26: {
            if (hitDir_ == null) {
              HitDir = new global::Weedwacker.Shared.Network.Proto.Vector();
            }
            input.ReadMessage(HitDir);
            break;
          }
          case 40: {
            HitColliderType = (global::Weedwacker.Shared.Network.Proto.HitColliderType) input.ReadEnum();
            break;
          }
          case 61: {
            Unk3300LNHIOLFMGCN = input.ReadFloat();
            break;
          }
          case 64: {
            HitBoxIndex = input.ReadInt32();
            break;
          }
          case 85: {
            Unk3300OJHBMLIAPJN = input.ReadFloat();
            break;
          }
          case 114: {
            if (hitPoint_ == null) {
              HitPoint = new global::Weedwacker.Shared.Network.Proto.Vector();
            }
            input.ReadMessage(HitPoint);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
