// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LuaShellNotifyType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from LuaShellNotifyType.proto</summary>
  public static partial class LuaShellNotifyTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for LuaShellNotifyType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LuaShellNotifyTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhMdWFTaGVsbE5vdGlmeVR5cGUucHJvdG8SH1dlZWR3YWNrZXIuU2hhcmVk",
            "Lk5ldHdvcmsuUHJvdG8qaAoSTHVhU2hlbGxOb3RpZnlUeXBlEikKJUxVQV9T",
            "SEVMTF9OT1RJRllfVFlQRV9MVUFTSEVMTF9OT1RJRlkQABInCiNMVUFfU0hF",
            "TExfTk9USUZZX1RZUEVfTFVBU0hFTExfSElERRABYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Weedwacker.Shared.Network.Proto.LuaShellNotifyType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum LuaShellNotifyType {
    [pbr::OriginalName("LUA_SHELL_NOTIFY_TYPE_LUASHELL_NOTIFY")] LuashellNotify = 0,
    [pbr::OriginalName("LUA_SHELL_NOTIFY_TYPE_LUASHELL_HIDE")] LuashellHide = 1,
  }

  #endregion

}

#endregion Designer generated code
