// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MiracleRingDeliverItemRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from MiracleRingDeliverItemRsp.proto</summary>
  public static partial class MiracleRingDeliverItemRspReflection {

    #region Descriptor
    /// <summary>File descriptor for MiracleRingDeliverItemRsp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MiracleRingDeliverItemRspReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9NaXJhY2xlUmluZ0RlbGl2ZXJJdGVtUnNwLnByb3RvEh9XZWVkd2Fja2Vy",
            "LlNoYXJlZC5OZXR3b3JrLlByb3RvGhFJbnRlck9wVHlwZS5wcm90bxoSSW50",
            "ZXJhY3RUeXBlLnByb3RvIt4BChlNaXJhY2xlUmluZ0RlbGl2ZXJJdGVtUnNw",
            "EhEKCWdhZGdldF9pZBgCIAEoDRI9CgdvcF90eXBlGAYgASgOMiwuV2VlZHdh",
            "Y2tlci5TaGFyZWQuTmV0d29yay5Qcm90by5JbnRlck9wVHlwZRIYChBnYWRn",
            "ZXRfZW50aXR5X2lkGA0gASgNEg8KB3JldGNvZGUYDyABKAUSRAoNaW50ZXJh",
            "Y3RfdHlwZRgMIAEoDjItLldlZWR3YWNrZXIuU2hhcmVkLk5ldHdvcmsuUHJv",
            "dG8uSW50ZXJhY3RUeXBlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Weedwacker.Shared.Network.Proto.InterOpTypeReflection.Descriptor, global::Weedwacker.Shared.Network.Proto.InteractTypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Shared.Network.Proto.MiracleRingDeliverItemRsp), global::Weedwacker.Shared.Network.Proto.MiracleRingDeliverItemRsp.Parser, new[]{ "GadgetId", "OpType", "GadgetEntityId", "Retcode", "InteractType" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// enum CmdId {
  ///   option allow_alias = true;
  ///   NONE = 0;
  ///   CMD_ID = 5217;
  ///   ENET_CHANNEL_ID = 0;
  ///   ENET_IS_RELIABLE = 1;
  /// }
  /// </summary>
  public sealed partial class MiracleRingDeliverItemRsp : pb::IMessage<MiracleRingDeliverItemRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MiracleRingDeliverItemRsp> _parser = new pb::MessageParser<MiracleRingDeliverItemRsp>(() => new MiracleRingDeliverItemRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MiracleRingDeliverItemRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Shared.Network.Proto.MiracleRingDeliverItemRspReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MiracleRingDeliverItemRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MiracleRingDeliverItemRsp(MiracleRingDeliverItemRsp other) : this() {
      gadgetId_ = other.gadgetId_;
      opType_ = other.opType_;
      gadgetEntityId_ = other.gadgetEntityId_;
      retcode_ = other.retcode_;
      interactType_ = other.interactType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MiracleRingDeliverItemRsp Clone() {
      return new MiracleRingDeliverItemRsp(this);
    }

    /// <summary>Field number for the "gadget_id" field.</summary>
    public const int GadgetIdFieldNumber = 2;
    private uint gadgetId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GadgetId {
      get { return gadgetId_; }
      set {
        gadgetId_ = value;
      }
    }

    /// <summary>Field number for the "op_type" field.</summary>
    public const int OpTypeFieldNumber = 6;
    private global::Weedwacker.Shared.Network.Proto.InterOpType opType_ = global::Weedwacker.Shared.Network.Proto.InterOpType.Finish;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Shared.Network.Proto.InterOpType OpType {
      get { return opType_; }
      set {
        opType_ = value;
      }
    }

    /// <summary>Field number for the "gadget_entity_id" field.</summary>
    public const int GadgetEntityIdFieldNumber = 13;
    private uint gadgetEntityId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GadgetEntityId {
      get { return gadgetEntityId_; }
      set {
        gadgetEntityId_ = value;
      }
    }

    /// <summary>Field number for the "retcode" field.</summary>
    public const int RetcodeFieldNumber = 15;
    private int retcode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Retcode {
      get { return retcode_; }
      set {
        retcode_ = value;
      }
    }

    /// <summary>Field number for the "interact_type" field.</summary>
    public const int InteractTypeFieldNumber = 12;
    private global::Weedwacker.Shared.Network.Proto.InteractType interactType_ = global::Weedwacker.Shared.Network.Proto.InteractType.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Shared.Network.Proto.InteractType InteractType {
      get { return interactType_; }
      set {
        interactType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MiracleRingDeliverItemRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MiracleRingDeliverItemRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GadgetId != other.GadgetId) return false;
      if (OpType != other.OpType) return false;
      if (GadgetEntityId != other.GadgetEntityId) return false;
      if (Retcode != other.Retcode) return false;
      if (InteractType != other.InteractType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GadgetId != 0) hash ^= GadgetId.GetHashCode();
      if (OpType != global::Weedwacker.Shared.Network.Proto.InterOpType.Finish) hash ^= OpType.GetHashCode();
      if (GadgetEntityId != 0) hash ^= GadgetEntityId.GetHashCode();
      if (Retcode != 0) hash ^= Retcode.GetHashCode();
      if (InteractType != global::Weedwacker.Shared.Network.Proto.InteractType.None) hash ^= InteractType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (GadgetId != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(GadgetId);
      }
      if (OpType != global::Weedwacker.Shared.Network.Proto.InterOpType.Finish) {
        output.WriteRawTag(48);
        output.WriteEnum((int) OpType);
      }
      if (InteractType != global::Weedwacker.Shared.Network.Proto.InteractType.None) {
        output.WriteRawTag(96);
        output.WriteEnum((int) InteractType);
      }
      if (GadgetEntityId != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(GadgetEntityId);
      }
      if (Retcode != 0) {
        output.WriteRawTag(120);
        output.WriteInt32(Retcode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (GadgetId != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(GadgetId);
      }
      if (OpType != global::Weedwacker.Shared.Network.Proto.InterOpType.Finish) {
        output.WriteRawTag(48);
        output.WriteEnum((int) OpType);
      }
      if (InteractType != global::Weedwacker.Shared.Network.Proto.InteractType.None) {
        output.WriteRawTag(96);
        output.WriteEnum((int) InteractType);
      }
      if (GadgetEntityId != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(GadgetEntityId);
      }
      if (Retcode != 0) {
        output.WriteRawTag(120);
        output.WriteInt32(Retcode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GadgetId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GadgetId);
      }
      if (OpType != global::Weedwacker.Shared.Network.Proto.InterOpType.Finish) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) OpType);
      }
      if (GadgetEntityId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GadgetEntityId);
      }
      if (Retcode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Retcode);
      }
      if (InteractType != global::Weedwacker.Shared.Network.Proto.InteractType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) InteractType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MiracleRingDeliverItemRsp other) {
      if (other == null) {
        return;
      }
      if (other.GadgetId != 0) {
        GadgetId = other.GadgetId;
      }
      if (other.OpType != global::Weedwacker.Shared.Network.Proto.InterOpType.Finish) {
        OpType = other.OpType;
      }
      if (other.GadgetEntityId != 0) {
        GadgetEntityId = other.GadgetEntityId;
      }
      if (other.Retcode != 0) {
        Retcode = other.Retcode;
      }
      if (other.InteractType != global::Weedwacker.Shared.Network.Proto.InteractType.None) {
        InteractType = other.InteractType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            GadgetId = input.ReadUInt32();
            break;
          }
          case 48: {
            OpType = (global::Weedwacker.Shared.Network.Proto.InterOpType) input.ReadEnum();
            break;
          }
          case 96: {
            InteractType = (global::Weedwacker.Shared.Network.Proto.InteractType) input.ReadEnum();
            break;
          }
          case 104: {
            GadgetEntityId = input.ReadUInt32();
            break;
          }
          case 120: {
            Retcode = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 16: {
            GadgetId = input.ReadUInt32();
            break;
          }
          case 48: {
            OpType = (global::Weedwacker.Shared.Network.Proto.InterOpType) input.ReadEnum();
            break;
          }
          case 96: {
            InteractType = (global::Weedwacker.Shared.Network.Proto.InteractType) input.ReadEnum();
            break;
          }
          case 104: {
            GadgetEntityId = input.ReadUInt32();
            break;
          }
          case 120: {
            Retcode = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
