// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PlayerHomeCompInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from PlayerHomeCompInfo.proto</summary>
  public static partial class PlayerHomeCompInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for PlayerHomeCompInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerHomeCompInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhQbGF5ZXJIb21lQ29tcEluZm8ucHJvdG8SH1dlZWR3YWNrZXIuU2hhcmVk",
            "Lk5ldHdvcmsuUHJvdG8aG0ZyaWVuZEVudGVySG9tZU9wdGlvbi5wcm90byLF",
            "AQoSUGxheWVySG9tZUNvbXBJbmZvElgKGGZyaWVuZF9lbnRlcl9ob21lX29w",
            "dGlvbhgNIAEoDjI2LldlZWR3YWNrZXIuU2hhcmVkLk5ldHdvcmsuUHJvdG8u",
            "RnJpZW5kRW50ZXJIb21lT3B0aW9uEhsKE3NlZW5fbW9kdWxlX2lkX2xpc3QY",
            "BSADKA0SGwoTVW5rMzMwMF9QQkVGSUpDRUtNSBgCIAMoDRIbChNVbmszMzAw",
            "X0pKUENGUEFLRkxNGAsgAygNYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Weedwacker.Shared.Network.Proto.FriendEnterHomeOptionReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Shared.Network.Proto.PlayerHomeCompInfo), global::Weedwacker.Shared.Network.Proto.PlayerHomeCompInfo.Parser, new[]{ "FriendEnterHomeOption", "SeenModuleIdList", "Unk3300PBEFIJCEKMH", "Unk3300JJPCFPAKFLM" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PlayerHomeCompInfo : pb::IMessage<PlayerHomeCompInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerHomeCompInfo> _parser = new pb::MessageParser<PlayerHomeCompInfo>(() => new PlayerHomeCompInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerHomeCompInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Shared.Network.Proto.PlayerHomeCompInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerHomeCompInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerHomeCompInfo(PlayerHomeCompInfo other) : this() {
      friendEnterHomeOption_ = other.friendEnterHomeOption_;
      seenModuleIdList_ = other.seenModuleIdList_.Clone();
      unk3300PBEFIJCEKMH_ = other.unk3300PBEFIJCEKMH_.Clone();
      unk3300JJPCFPAKFLM_ = other.unk3300JJPCFPAKFLM_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerHomeCompInfo Clone() {
      return new PlayerHomeCompInfo(this);
    }

    /// <summary>Field number for the "friend_enter_home_option" field.</summary>
    public const int FriendEnterHomeOptionFieldNumber = 13;
    private global::Weedwacker.Shared.Network.Proto.FriendEnterHomeOption friendEnterHomeOption_ = global::Weedwacker.Shared.Network.Proto.FriendEnterHomeOption.NeedConfirm;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Shared.Network.Proto.FriendEnterHomeOption FriendEnterHomeOption {
      get { return friendEnterHomeOption_; }
      set {
        friendEnterHomeOption_ = value;
      }
    }

    /// <summary>Field number for the "seen_module_id_list" field.</summary>
    public const int SeenModuleIdListFieldNumber = 5;
    private static readonly pb::FieldCodec<uint> _repeated_seenModuleIdList_codec
        = pb::FieldCodec.ForUInt32(42);
    private readonly pbc::RepeatedField<uint> seenModuleIdList_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> SeenModuleIdList {
      get { return seenModuleIdList_; }
    }

    /// <summary>Field number for the "Unk3300_PBEFIJCEKMH" field.</summary>
    public const int Unk3300PBEFIJCEKMHFieldNumber = 2;
    private static readonly pb::FieldCodec<uint> _repeated_unk3300PBEFIJCEKMH_codec
        = pb::FieldCodec.ForUInt32(18);
    private readonly pbc::RepeatedField<uint> unk3300PBEFIJCEKMH_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> Unk3300PBEFIJCEKMH {
      get { return unk3300PBEFIJCEKMH_; }
    }

    /// <summary>Field number for the "Unk3300_JJPCFPAKFLM" field.</summary>
    public const int Unk3300JJPCFPAKFLMFieldNumber = 11;
    private static readonly pb::FieldCodec<uint> _repeated_unk3300JJPCFPAKFLM_codec
        = pb::FieldCodec.ForUInt32(90);
    private readonly pbc::RepeatedField<uint> unk3300JJPCFPAKFLM_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> Unk3300JJPCFPAKFLM {
      get { return unk3300JJPCFPAKFLM_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerHomeCompInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerHomeCompInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FriendEnterHomeOption != other.FriendEnterHomeOption) return false;
      if(!seenModuleIdList_.Equals(other.seenModuleIdList_)) return false;
      if(!unk3300PBEFIJCEKMH_.Equals(other.unk3300PBEFIJCEKMH_)) return false;
      if(!unk3300JJPCFPAKFLM_.Equals(other.unk3300JJPCFPAKFLM_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FriendEnterHomeOption != global::Weedwacker.Shared.Network.Proto.FriendEnterHomeOption.NeedConfirm) hash ^= FriendEnterHomeOption.GetHashCode();
      hash ^= seenModuleIdList_.GetHashCode();
      hash ^= unk3300PBEFIJCEKMH_.GetHashCode();
      hash ^= unk3300JJPCFPAKFLM_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      unk3300PBEFIJCEKMH_.WriteTo(output, _repeated_unk3300PBEFIJCEKMH_codec);
      seenModuleIdList_.WriteTo(output, _repeated_seenModuleIdList_codec);
      unk3300JJPCFPAKFLM_.WriteTo(output, _repeated_unk3300JJPCFPAKFLM_codec);
      if (FriendEnterHomeOption != global::Weedwacker.Shared.Network.Proto.FriendEnterHomeOption.NeedConfirm) {
        output.WriteRawTag(104);
        output.WriteEnum((int) FriendEnterHomeOption);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      unk3300PBEFIJCEKMH_.WriteTo(ref output, _repeated_unk3300PBEFIJCEKMH_codec);
      seenModuleIdList_.WriteTo(ref output, _repeated_seenModuleIdList_codec);
      unk3300JJPCFPAKFLM_.WriteTo(ref output, _repeated_unk3300JJPCFPAKFLM_codec);
      if (FriendEnterHomeOption != global::Weedwacker.Shared.Network.Proto.FriendEnterHomeOption.NeedConfirm) {
        output.WriteRawTag(104);
        output.WriteEnum((int) FriendEnterHomeOption);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FriendEnterHomeOption != global::Weedwacker.Shared.Network.Proto.FriendEnterHomeOption.NeedConfirm) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) FriendEnterHomeOption);
      }
      size += seenModuleIdList_.CalculateSize(_repeated_seenModuleIdList_codec);
      size += unk3300PBEFIJCEKMH_.CalculateSize(_repeated_unk3300PBEFIJCEKMH_codec);
      size += unk3300JJPCFPAKFLM_.CalculateSize(_repeated_unk3300JJPCFPAKFLM_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerHomeCompInfo other) {
      if (other == null) {
        return;
      }
      if (other.FriendEnterHomeOption != global::Weedwacker.Shared.Network.Proto.FriendEnterHomeOption.NeedConfirm) {
        FriendEnterHomeOption = other.FriendEnterHomeOption;
      }
      seenModuleIdList_.Add(other.seenModuleIdList_);
      unk3300PBEFIJCEKMH_.Add(other.unk3300PBEFIJCEKMH_);
      unk3300JJPCFPAKFLM_.Add(other.unk3300JJPCFPAKFLM_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18:
          case 16: {
            unk3300PBEFIJCEKMH_.AddEntriesFrom(input, _repeated_unk3300PBEFIJCEKMH_codec);
            break;
          }
          case 42:
          case 40: {
            seenModuleIdList_.AddEntriesFrom(input, _repeated_seenModuleIdList_codec);
            break;
          }
          case 90:
          case 88: {
            unk3300JJPCFPAKFLM_.AddEntriesFrom(input, _repeated_unk3300JJPCFPAKFLM_codec);
            break;
          }
          case 104: {
            FriendEnterHomeOption = (global::Weedwacker.Shared.Network.Proto.FriendEnterHomeOption) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18:
          case 16: {
            unk3300PBEFIJCEKMH_.AddEntriesFrom(ref input, _repeated_unk3300PBEFIJCEKMH_codec);
            break;
          }
          case 42:
          case 40: {
            seenModuleIdList_.AddEntriesFrom(ref input, _repeated_seenModuleIdList_codec);
            break;
          }
          case 90:
          case 88: {
            unk3300JJPCFPAKFLM_.AddEntriesFrom(ref input, _repeated_unk3300JJPCFPAKFLM_codec);
            break;
          }
          case 104: {
            FriendEnterHomeOption = (global::Weedwacker.Shared.Network.Proto.FriendEnterHomeOption) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
