// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SalvagePreventStopReason.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from SalvagePreventStopReason.proto</summary>
  public static partial class SalvagePreventStopReasonReflection {

    #region Descriptor
    /// <summary>File descriptor for SalvagePreventStopReason.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SalvagePreventStopReasonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5TYWx2YWdlUHJldmVudFN0b3BSZWFzb24ucHJvdG8SH1dlZWR3YWNrZXIu",
            "U2hhcmVkLk5ldHdvcmsuUHJvdG8qsAIKGFNhbHZhZ2VQcmV2ZW50U3RvcFJl",
            "YXNvbhIkCiBTQUxWQUdFX1BSRVZFTlRfU1RPUF9SRUFTT05fTk9ORRAAEicK",
            "I1NBTFZBR0VfUFJFVkVOVF9TVE9QX1JFQVNPTl9TVUNDRVNTEAESJwojU0FM",
            "VkFHRV9QUkVWRU5UX1NUT1BfUkVBU09OX0FSUklWQUwQAhIpCiVTQUxWQUdF",
            "X1BSRVZFTlRfU1RPUF9SRUFTT05fSU5URVJSVVBUEAMSJQohU0FMVkFHRV9Q",
            "UkVWRU5UX1NUT1BfUkVBU09OX0xFQVZFEAQSJAogU0FMVkFHRV9QUkVWRU5U",
            "X1NUT1BfUkVBU09OX0ZVTEwQBRIkCiBTQUxWQUdFX1BSRVZFTlRfU1RPUF9S",
            "RUFTT05fQVdBWRAGYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Weedwacker.Shared.Network.Proto.SalvagePreventStopReason), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum SalvagePreventStopReason {
    [pbr::OriginalName("SALVAGE_PREVENT_STOP_REASON_NONE")] None = 0,
    [pbr::OriginalName("SALVAGE_PREVENT_STOP_REASON_SUCCESS")] Success = 1,
    [pbr::OriginalName("SALVAGE_PREVENT_STOP_REASON_ARRIVAL")] Arrival = 2,
    [pbr::OriginalName("SALVAGE_PREVENT_STOP_REASON_INTERRUPT")] Interrupt = 3,
    [pbr::OriginalName("SALVAGE_PREVENT_STOP_REASON_LEAVE")] Leave = 4,
    [pbr::OriginalName("SALVAGE_PREVENT_STOP_REASON_FULL")] Full = 5,
    [pbr::OriginalName("SALVAGE_PREVENT_STOP_REASON_AWAY")] Away = 6,
  }

  #endregion

}

#endregion Designer generated code
