// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SceneGallerySalvageEscortInfoInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from SceneGallerySalvageEscortInfoInfo.proto</summary>
  public static partial class SceneGallerySalvageEscortInfoInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for SceneGallerySalvageEscortInfoInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SceneGallerySalvageEscortInfoInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CidTY2VuZUdhbGxlcnlTYWx2YWdlRXNjb3J0SW5mb0luZm8ucHJvdG8ifwoh",
            "U2NlbmVHYWxsZXJ5U2FsdmFnZUVzY29ydEluZm9JbmZvEhUKDW1heF9ib3hf",
            "Y291bnQYDiABKA0SGQoRbWF4X21vbnN0ZXJfY291bnQYAyABKA0SEQoJYm94",
            "X2NvdW50GAcgASgNEhUKDW1vbnN0ZXJfY291bnQYCyABKA1CIqoCH1dlZWR3",
            "YWNrZXIuU2hhcmVkLk5ldHdvcmsuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Shared.Network.Proto.SceneGallerySalvageEscortInfoInfo), global::Weedwacker.Shared.Network.Proto.SceneGallerySalvageEscortInfoInfo.Parser, new[]{ "MaxBoxCount", "MaxMonsterCount", "BoxCount", "MonsterCount" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SceneGallerySalvageEscortInfoInfo : pb::IMessage<SceneGallerySalvageEscortInfoInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SceneGallerySalvageEscortInfoInfo> _parser = new pb::MessageParser<SceneGallerySalvageEscortInfoInfo>(() => new SceneGallerySalvageEscortInfoInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SceneGallerySalvageEscortInfoInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Shared.Network.Proto.SceneGallerySalvageEscortInfoInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SceneGallerySalvageEscortInfoInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SceneGallerySalvageEscortInfoInfo(SceneGallerySalvageEscortInfoInfo other) : this() {
      maxBoxCount_ = other.maxBoxCount_;
      maxMonsterCount_ = other.maxMonsterCount_;
      boxCount_ = other.boxCount_;
      monsterCount_ = other.monsterCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SceneGallerySalvageEscortInfoInfo Clone() {
      return new SceneGallerySalvageEscortInfoInfo(this);
    }

    /// <summary>Field number for the "max_box_count" field.</summary>
    public const int MaxBoxCountFieldNumber = 14;
    private uint maxBoxCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MaxBoxCount {
      get { return maxBoxCount_; }
      set {
        maxBoxCount_ = value;
      }
    }

    /// <summary>Field number for the "max_monster_count" field.</summary>
    public const int MaxMonsterCountFieldNumber = 3;
    private uint maxMonsterCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MaxMonsterCount {
      get { return maxMonsterCount_; }
      set {
        maxMonsterCount_ = value;
      }
    }

    /// <summary>Field number for the "box_count" field.</summary>
    public const int BoxCountFieldNumber = 7;
    private uint boxCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BoxCount {
      get { return boxCount_; }
      set {
        boxCount_ = value;
      }
    }

    /// <summary>Field number for the "monster_count" field.</summary>
    public const int MonsterCountFieldNumber = 11;
    private uint monsterCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MonsterCount {
      get { return monsterCount_; }
      set {
        monsterCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SceneGallerySalvageEscortInfoInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SceneGallerySalvageEscortInfoInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MaxBoxCount != other.MaxBoxCount) return false;
      if (MaxMonsterCount != other.MaxMonsterCount) return false;
      if (BoxCount != other.BoxCount) return false;
      if (MonsterCount != other.MonsterCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MaxBoxCount != 0) hash ^= MaxBoxCount.GetHashCode();
      if (MaxMonsterCount != 0) hash ^= MaxMonsterCount.GetHashCode();
      if (BoxCount != 0) hash ^= BoxCount.GetHashCode();
      if (MonsterCount != 0) hash ^= MonsterCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MaxMonsterCount != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(MaxMonsterCount);
      }
      if (BoxCount != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(BoxCount);
      }
      if (MonsterCount != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(MonsterCount);
      }
      if (MaxBoxCount != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(MaxBoxCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MaxMonsterCount != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(MaxMonsterCount);
      }
      if (BoxCount != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(BoxCount);
      }
      if (MonsterCount != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(MonsterCount);
      }
      if (MaxBoxCount != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(MaxBoxCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MaxBoxCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MaxBoxCount);
      }
      if (MaxMonsterCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MaxMonsterCount);
      }
      if (BoxCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BoxCount);
      }
      if (MonsterCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MonsterCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SceneGallerySalvageEscortInfoInfo other) {
      if (other == null) {
        return;
      }
      if (other.MaxBoxCount != 0) {
        MaxBoxCount = other.MaxBoxCount;
      }
      if (other.MaxMonsterCount != 0) {
        MaxMonsterCount = other.MaxMonsterCount;
      }
      if (other.BoxCount != 0) {
        BoxCount = other.BoxCount;
      }
      if (other.MonsterCount != 0) {
        MonsterCount = other.MonsterCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 24: {
            MaxMonsterCount = input.ReadUInt32();
            break;
          }
          case 56: {
            BoxCount = input.ReadUInt32();
            break;
          }
          case 88: {
            MonsterCount = input.ReadUInt32();
            break;
          }
          case 112: {
            MaxBoxCount = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 24: {
            MaxMonsterCount = input.ReadUInt32();
            break;
          }
          case 56: {
            BoxCount = input.ReadUInt32();
            break;
          }
          case 88: {
            MonsterCount = input.ReadUInt32();
            break;
          }
          case 112: {
            MaxBoxCount = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
