// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SceneGalleryHideAndSeekInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from SceneGalleryHideAndSeekInfo.proto</summary>
  public static partial class SceneGalleryHideAndSeekInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for SceneGalleryHideAndSeekInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SceneGalleryHideAndSeekInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFTY2VuZUdhbGxlcnlIaWRlQW5kU2Vla0luZm8ucHJvdG8SH1dlZWR3YWNr",
            "ZXIuU2hhcmVkLk5ldHdvcmsuUHJvdG8iVwobU2NlbmVHYWxsZXJ5SGlkZUFu",
            "ZFNlZWtJbmZvEhsKE1VuazMzMDBfTEhNSEFMS0RCQk4YCiADKA0SGwoTVW5r",
            "MzMwMF9DTkxLTUdGRkFFQxgHIAMoDWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Shared.Network.Proto.SceneGalleryHideAndSeekInfo), global::Weedwacker.Shared.Network.Proto.SceneGalleryHideAndSeekInfo.Parser, new[]{ "Unk3300LHMHALKDBBN", "Unk3300CNLKMGFFAEC" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SceneGalleryHideAndSeekInfo : pb::IMessage<SceneGalleryHideAndSeekInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SceneGalleryHideAndSeekInfo> _parser = new pb::MessageParser<SceneGalleryHideAndSeekInfo>(() => new SceneGalleryHideAndSeekInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SceneGalleryHideAndSeekInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Shared.Network.Proto.SceneGalleryHideAndSeekInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SceneGalleryHideAndSeekInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SceneGalleryHideAndSeekInfo(SceneGalleryHideAndSeekInfo other) : this() {
      unk3300LHMHALKDBBN_ = other.unk3300LHMHALKDBBN_.Clone();
      unk3300CNLKMGFFAEC_ = other.unk3300CNLKMGFFAEC_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SceneGalleryHideAndSeekInfo Clone() {
      return new SceneGalleryHideAndSeekInfo(this);
    }

    /// <summary>Field number for the "Unk3300_LHMHALKDBBN" field.</summary>
    public const int Unk3300LHMHALKDBBNFieldNumber = 10;
    private static readonly pb::FieldCodec<uint> _repeated_unk3300LHMHALKDBBN_codec
        = pb::FieldCodec.ForUInt32(82);
    private readonly pbc::RepeatedField<uint> unk3300LHMHALKDBBN_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> Unk3300LHMHALKDBBN {
      get { return unk3300LHMHALKDBBN_; }
    }

    /// <summary>Field number for the "Unk3300_CNLKMGFFAEC" field.</summary>
    public const int Unk3300CNLKMGFFAECFieldNumber = 7;
    private static readonly pb::FieldCodec<uint> _repeated_unk3300CNLKMGFFAEC_codec
        = pb::FieldCodec.ForUInt32(58);
    private readonly pbc::RepeatedField<uint> unk3300CNLKMGFFAEC_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> Unk3300CNLKMGFFAEC {
      get { return unk3300CNLKMGFFAEC_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SceneGalleryHideAndSeekInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SceneGalleryHideAndSeekInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!unk3300LHMHALKDBBN_.Equals(other.unk3300LHMHALKDBBN_)) return false;
      if(!unk3300CNLKMGFFAEC_.Equals(other.unk3300CNLKMGFFAEC_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= unk3300LHMHALKDBBN_.GetHashCode();
      hash ^= unk3300CNLKMGFFAEC_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      unk3300CNLKMGFFAEC_.WriteTo(output, _repeated_unk3300CNLKMGFFAEC_codec);
      unk3300LHMHALKDBBN_.WriteTo(output, _repeated_unk3300LHMHALKDBBN_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      unk3300CNLKMGFFAEC_.WriteTo(ref output, _repeated_unk3300CNLKMGFFAEC_codec);
      unk3300LHMHALKDBBN_.WriteTo(ref output, _repeated_unk3300LHMHALKDBBN_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += unk3300LHMHALKDBBN_.CalculateSize(_repeated_unk3300LHMHALKDBBN_codec);
      size += unk3300CNLKMGFFAEC_.CalculateSize(_repeated_unk3300CNLKMGFFAEC_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SceneGalleryHideAndSeekInfo other) {
      if (other == null) {
        return;
      }
      unk3300LHMHALKDBBN_.Add(other.unk3300LHMHALKDBBN_);
      unk3300CNLKMGFFAEC_.Add(other.unk3300CNLKMGFFAEC_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 58:
          case 56: {
            unk3300CNLKMGFFAEC_.AddEntriesFrom(input, _repeated_unk3300CNLKMGFFAEC_codec);
            break;
          }
          case 82:
          case 80: {
            unk3300LHMHALKDBBN_.AddEntriesFrom(input, _repeated_unk3300LHMHALKDBBN_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 58:
          case 56: {
            unk3300CNLKMGFFAEC_.AddEntriesFrom(ref input, _repeated_unk3300CNLKMGFFAEC_codec);
            break;
          }
          case 82:
          case 80: {
            unk3300LHMHALKDBBN_.AddEntriesFrom(ref input, _repeated_unk3300LHMHALKDBBN_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
