// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WatcherChangeNotify.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from WatcherChangeNotify.proto</summary>
  public static partial class WatcherChangeNotifyReflection {

    #region Descriptor
    /// <summary>File descriptor for WatcherChangeNotify.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WatcherChangeNotifyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlXYXRjaGVyQ2hhbmdlTm90aWZ5LnByb3RvEh9XZWVkd2Fja2VyLlNoYXJl",
            "ZC5OZXR3b3JrLlByb3RvIk8KE1dhdGNoZXJDaGFuZ2VOb3RpZnkSGwoTVW5r",
            "MzMwMF9FTEROT05PQ0ZNTRgKIAMoDRIbChNVbmszMzAwX0ZETUpBQ0ZNT0xH",
            "GAUgAygNYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Shared.Network.Proto.WatcherChangeNotify), global::Weedwacker.Shared.Network.Proto.WatcherChangeNotify.Parser, new[]{ "Unk3300ELDNONOCFMM", "Unk3300FDMJACFMOLG" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// enum CmdId {
  ///   option allow_alias = true;
  ///   NONE = 0;
  ///   CMD_ID = 2230;
  ///   ENET_CHANNEL_ID = 0;
  ///   ENET_IS_RELIABLE = 1;
  /// }
  /// </summary>
  public sealed partial class WatcherChangeNotify : pb::IMessage<WatcherChangeNotify>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WatcherChangeNotify> _parser = new pb::MessageParser<WatcherChangeNotify>(() => new WatcherChangeNotify());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WatcherChangeNotify> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Shared.Network.Proto.WatcherChangeNotifyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatcherChangeNotify() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatcherChangeNotify(WatcherChangeNotify other) : this() {
      unk3300ELDNONOCFMM_ = other.unk3300ELDNONOCFMM_.Clone();
      unk3300FDMJACFMOLG_ = other.unk3300FDMJACFMOLG_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatcherChangeNotify Clone() {
      return new WatcherChangeNotify(this);
    }

    /// <summary>Field number for the "Unk3300_ELDNONOCFMM" field.</summary>
    public const int Unk3300ELDNONOCFMMFieldNumber = 10;
    private static readonly pb::FieldCodec<uint> _repeated_unk3300ELDNONOCFMM_codec
        = pb::FieldCodec.ForUInt32(82);
    private readonly pbc::RepeatedField<uint> unk3300ELDNONOCFMM_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> Unk3300ELDNONOCFMM {
      get { return unk3300ELDNONOCFMM_; }
    }

    /// <summary>Field number for the "Unk3300_FDMJACFMOLG" field.</summary>
    public const int Unk3300FDMJACFMOLGFieldNumber = 5;
    private static readonly pb::FieldCodec<uint> _repeated_unk3300FDMJACFMOLG_codec
        = pb::FieldCodec.ForUInt32(42);
    private readonly pbc::RepeatedField<uint> unk3300FDMJACFMOLG_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> Unk3300FDMJACFMOLG {
      get { return unk3300FDMJACFMOLG_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WatcherChangeNotify);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WatcherChangeNotify other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!unk3300ELDNONOCFMM_.Equals(other.unk3300ELDNONOCFMM_)) return false;
      if(!unk3300FDMJACFMOLG_.Equals(other.unk3300FDMJACFMOLG_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= unk3300ELDNONOCFMM_.GetHashCode();
      hash ^= unk3300FDMJACFMOLG_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      unk3300FDMJACFMOLG_.WriteTo(output, _repeated_unk3300FDMJACFMOLG_codec);
      unk3300ELDNONOCFMM_.WriteTo(output, _repeated_unk3300ELDNONOCFMM_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      unk3300FDMJACFMOLG_.WriteTo(ref output, _repeated_unk3300FDMJACFMOLG_codec);
      unk3300ELDNONOCFMM_.WriteTo(ref output, _repeated_unk3300ELDNONOCFMM_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += unk3300ELDNONOCFMM_.CalculateSize(_repeated_unk3300ELDNONOCFMM_codec);
      size += unk3300FDMJACFMOLG_.CalculateSize(_repeated_unk3300FDMJACFMOLG_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WatcherChangeNotify other) {
      if (other == null) {
        return;
      }
      unk3300ELDNONOCFMM_.Add(other.unk3300ELDNONOCFMM_);
      unk3300FDMJACFMOLG_.Add(other.unk3300FDMJACFMOLG_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 42:
          case 40: {
            unk3300FDMJACFMOLG_.AddEntriesFrom(input, _repeated_unk3300FDMJACFMOLG_codec);
            break;
          }
          case 82:
          case 80: {
            unk3300ELDNONOCFMM_.AddEntriesFrom(input, _repeated_unk3300ELDNONOCFMM_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 42:
          case 40: {
            unk3300FDMJACFMOLG_.AddEntriesFrom(ref input, _repeated_unk3300FDMJACFMOLG_codec);
            break;
          }
          case 82:
          case 80: {
            unk3300ELDNONOCFMM_.AddEntriesFrom(ref input, _repeated_unk3300ELDNONOCFMM_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
